### ISSUE TITLE
Installation failed with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by barthel** [bitwarden/server#1039]
I've tried to install the server on my Macbook Pro (macOS Big Sur 11.1.0) using Docker Desktop.

```
$ ./bitwarden.sh install
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4, build 40524192

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): xxxxxxxxxx.xxxxxxxxxx.xx

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.38.2: Pulling from bitwarden/setup
Digest: sha256:23b82bdbbfe63b05030be166a1db98ee7fbfc11e1bae5bcef771403f7298ce41
Status: Image is up to date for bitwarden/setup:1.38.2
docker.io/bitwarden/setup:1.38.2

(!) Enter your installation id (get at https://bitwarden.com/host): xxxxxxxxxxxxxxxxxxx

(!) Enter your installation key: xxxxxxxxxxxxxxxxxxxxxx

(!) Do you have a SSL certificate to use? (y/n): y

!!!!!!!!!! NOTE !!!!!!!!!!
Make sure 'certificate.crt' and 'private.key' are provided in the 
appropriate directory before running 'start' (see docs for info).

(!) Is this a trusted SSL certificate (requires ca.crt, see docs)? (y/n): n

Generating key for IdentityServer.
Generating a RSA private key
..................................................................................................................................................................................................++++
................................++++
writing new private key to 'identity.key'
-----
pkcs12: Can't open "/bitwarden/identity/identity.pfx" for writing, Permission denied

!!!!!!!!!! WARNING !!!!!!!!!!
You are using an untrusted SSL certificate. This certificate will not be 
trusted by Bitwarden client applications. You must add this certificate to 
the trusted store on each device or else you will receive errors when trying 
to connect to your installation.

Building nginx config.
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/bitwarden/nginx/default.conf' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at Bit.Setup.NginxConfigBuilder.Build(TemplateModel model) in /home/runner/work/server/server/util/Setup/NginxConfigBuilder.cs:line 66
   at Bit.Setup.NginxConfigBuilder.BuildForInstaller() in /home/runner/work/server/server/util/Setup/NginxConfigBuilder.cs:line 47
   at Bit.Setup.Program.Install() in /home/runner/work/server/server/util/Setup/Program.cs:line 99
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 65
```
The entries in `bwdata/env/uid.env` are matching the real UID/GID.

```
LOCAL_UID=501
LOCAL_GID=20
```

```
$ ls -aln bwdata
total 0
drwxr-xr-x   10 501  20   320 Dec 16 16:44 .
drwxr-xr-x+ 122 501  20  3904 Dec 16 16:44 ..
drwxr-xr-x    2 501  20    64 Dec 16 16:44 ca-certificates
drwxr-xr-x    2 501  20    64 Dec 16 16:44 docker
drwxr-xr-x    3 501  20    96 Dec 16 16:44 env
drwxr-xr-x    2 501  20    64 Dec 16 16:44 identity
drwxr-xr-x    2 501  20    64 Dec 16 16:44 letsencrypt
drwxr-xr-x    2 501  20    64 Dec 16 16:44 nginx
drwxr-xr-x    3 501  20    96 Dec 16 16:44 scripts
drwxr-xr-x    3 501  20    96 Dec 16 16:45 ssl
```

**Comment by apmarshall** [comment]
What is the output of `ls -aln` in `/bitwarden` and `/bitwarden/nginx`?

**Comment by barthel** [comment]
I tried to recreate the issue again to answer your question @apmarshall .
With the current version, the issue no longer occurs.
```
1.38.4: Pulling from bitwarden/setup
Digest: sha256:d982b81ac6fdb95b0da8744b30b965045b3176201f48903526c3c04d4c6cf972
Status: Image is up to date for bitwarden/setup:1.38.4
docker.io/bitwarden/setup:1.38.4
```
