### ISSUE TITLE
Can't login on new devices anymore. "An unexpected error has occurred". 2FA issue? 

### ISSUE THREAD

**Issue by jakommo** [bitwarden/server#1333]
## Describe the Bug
Potentially a duplicate of https://github.com/bitwarden/server/issues/1332, but I'm hitting it on my self hosted docker install, thus creating a new issue in case it's a different one than https://github.com/bitwarden/server/issues/1332. Feel free to close if you think they are related.

Two days ago I updated my self hosted docker install via `./bitwarden.sh updateself && ./bitwarden.sh update`.
Since then I can't log in anymore on devices that are not authenticated already.
After entering my password, the loading wheel is spinning and then a `An unexpected error has occurred` pops up.
The devices where I'm logged in already still work and changes are synced. 

In the `bitwarden-identity` container I can see the following error:
```
warn: Microsoft.AspNetCore.Identity.UserManager[10]
      VerifyTwoFactorTokenAsync() failed for user aa72b8f6-6eab-4739-9ca5-a99701637705.
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: Value cannot be null. (Parameter 'json')
System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildTwoFactorParams(Organization organization, User user, TwoFactorProviderType type, TwoFactorProvider provider) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 429
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildTwoFactorResultAsync(User user, Organization organization, T context) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 213
   at Bit.Core.IdentityServer.BaseRequestValidator`1.ValidateAsync(T context, ValidatedTokenRequest request) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 112
   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/runner/work/server/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 48
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8NJVFITHRT", Request id "0HM8NJVFITHRT:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildTwoFactorParams(Organization organization, User user, TwoFactorProviderType type, TwoFactorProvider provider) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 429
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildTwoFactorResultAsync(User user, Organization organization, T context) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 213
   at Bit.Core.IdentityServer.BaseRequestValidator`1.ValidateAsync(T context, ValidatedTokenRequest request) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 112
   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/runner/work/server/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 48
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, ICurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 21
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Bit.Core.Utilities.ServiceCollectionExtensions.<>c__DisplayClass10_0.<<UseDefaultMiddleware>b__1>d.MoveNext() in /home/runner/work/server/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 459
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Bit.Identity.Startup.<>c__DisplayClass10_1.<<Configure>b__2>d.MoveNext() in /home/runner/work/server/server/src/Identity/Startup.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
I have `FIDO2 WebAuthn Enabled` on my account. My license expired a few days ago and I can't install the new one because I can't login to the web vault anymore. Already tried copying the new license file over the old one in `./bwdata/core/licenses/user/aa72b8f6-6eab-4739-9ca5-a99701637705.json` and restarting all containers, but that doesn't change anything and I'm not sure if copying the license file like this is supposed to work.

Initially I thought my issue is related to the license expiry, but seeing https://github.com/bitwarden/server/issues/1332, I'm not sure anymore. 
I have to add that I'm also using `FIDO2 WebAuthn` on vault.bitwarden.com and do not have any issues there. 

## Steps To Reproduce

Not sure how to repro. On my install it happens every time I try to login via web vault or via bitwarden-desktop on a device that was not authenticated before.

## Expected Result

Login to account and request fideo2 key button press 

## Actual Result

``An unexpected error has occurred

## Environment

- Operating system: `Ubuntu 20.04.2 LTS`
- Build Version: `1.41.2`
- Self Hosted: `true`
- Environment:  Docker: `20.10.5`
- Hardware: Intel i3 4 core / 8GB RAM

**Comment by eliykat** [comment]
Hi @jakommo, it appears that the recent server update has locked a few people out of their accounts if they were using a premium 2FA option and their premium subscription lapsed. Please contact our Customer Success team here: https://bitwarden.com/contact/. You can include a link to this issue in your message content. They will be able to re-enable premium for you so that you can regain access. (If anyone reading this has the same issue, please do the same.) Our dev team are working on a more permanent fix in the meantime.

**Comment by jakommo** [comment]
Upgrading to `1.41.3` soled it. Thanks for the quick fix.
