### ISSUE TITLE
Error when updating self-hosted: Property 'captcha' not found on type 'Bit.Setup.Configuration'.

### ISSUE THREAD

**Issue by Schnuecks** [bitwarden/server#1537]
Hi, tried to update with updateself and update this is the result
```
[bw@srvbw001]# ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.41.5
Docker version 20.10.8, build 3967b7d
docker-compose version 1.27.4, build 40524192

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
1.41.5: Pulling from bitwarden/setup
Digest: sha256:61bccecff30edb5e8b936076eace064adb6aa082baa160c7d25f16946296d409
Status: Image is up to date for bitwarden/setup:1.41.5
docker.io/bitwarden/setup:1.41.5

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'captcha' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 121
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 272
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 143
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 65

```

**Comment by Hinton** [comment]
@Schnuecks That's a slightly weird error. It seems to be trying to deserialize a `captcha` property which didn't exist on the config object in release `1.41.5`. What release did you try to upgrade from? (the field was added later though).

**Comment by Schnuecks** [comment]
We had some weird problems with this server, we had to reinstall and since then all is running fine, no error occoured on any update since. Think we could close it here. Thanks for reminding :)
