### ISSUE TITLE
server performance degraded since installing 1.42.2

### ISSUE THREAD

**Issue by valerioa** [bitwarden/server#1554]
## Describe the Bug

Server performance is noticeably degraded since installing 1.42.2 - easy to notice in the firefox add-on 

## Steps To Reproduce

Use any version prior to 1.42.2: password list display very fast when accessing a website. Since 1.42.2 was installed, a list of logins can take up to 3-5 seconds to display. Server on LAN

1. Open a website for which you have at least one username/password pait
2. Click on bitwarden addon
3. wait 3-5 seconds for list to appear

## Expected Result

U/P pairs used to appear immediately, no wait time

## Environment

- Operating system: Ubuntu 20.0.4
- Build Version: 1.42.2
- Self Hosted: true
- Environment: docker
- Hardware: AMD A10-5800K 4 cores 32GB RAM

## Additional Context

The only thing I have noticed is that I have a lot of these errors in the server notification logs. I get one every few milliseconds

They are not present in the notification logs prior to 1.42.2

```
2021-08-30 18:21:54.736 +00:00 [Error] Error when dispatching '"OnConnectedAsync"' on hub.
System.InvalidOperationException: Unable to resolve service for type 'Bit.Core.Repositories.IProviderUserRepository' while attempting to activate 'Bit.Notifications.NotificationsHub'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method79(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```
I wonder is this error slows down api calls

Clearly it started when I installed 1.42.2

```
ls -l /bitwarden/bwdata/logs/notifications/Notifications/
-rw-r--r-- 1 nobody nogroup       454 Mar 24 09:44 20210324.txt
-rw-r--r-- 1 nobody nogroup       687 Mar 27 13:56 20210327.txt
-rw-r--r-- 1 nobody nogroup       746 Apr 11 21:31 20210412.txt
-rw-r--r-- 1 nobody nogroup       687 Apr 27 10:11 20210427.txt
-rw-r--r-- 1 nobody nogroup       454 May  6 07:13 20210506.txt
-rw-r--r-- 1 nobody nogroup      1681 May 10 12:33 20210510.txt
-rw-r--r-- 1 nobody nogroup      2633 May 10 21:28 20210511.txt
-rw-r--r-- 1 nobody nogroup       687 May 15 07:15 20210515.txt
-rw-r--r-- 1 nobody nogroup       687 May 26 08:36 20210526.txt
-rw-r--r-- 1 nobody nogroup       687 May 30 12:26 20210530.txt
-rw-r--r-- 1 nobody nogroup      8700 Jun  7 16:56 20210607.txt
-rw-r--r-- 1 nobody nogroup       746 Jun 25 19:22 20210626.txt
-rw-r--r-- 1 nobody nogroup       687 Jun 30 13:42 20210630.txt
-rw-r--r-- 1 nobody nogroup       687 Jul  1 17:02 20210701.txt
-rw-r--r-- 1 nobody nogroup       687 Jul  2 21:18 20210703.txt
-rw-r--r-- 1 nobody nogroup       687 Jul  9 20:19 20210710.txt
-rw-r--r-- 1 nobody nogroup      1200 Jul 15 10:54 20210715.txt
-rw-r--r-- 1 nobody nogroup       687 Jul 25 16:02 20210725.txt
-rw-r--r-- 1 nobody nogroup       746 Jul 25 21:27 20210726.txt
-rw-r--r-- 1 nobody nogroup       292 Jul 27 06:47 20210727.txt
-rw-r--r-- 1 nobody nogroup       687 Jul 31 14:35 20210731.txt
-rw-r--r-- 1 nobody nogroup      1038 Aug  5 14:37 20210805.txt
-rw-r--r-- 1 nobody nogroup       292 Aug 15 06:59 20210815.txt
-rw-r--r-- 1 nobody nogroup       395 Aug 20 13:45 20210820.txt
-rw-r--r-- 1 nobody nogroup       292 Aug 20 22:13 20210821.txt
-rw-r--r-- 1 nobody nogroup       849 Aug 23 17:16 20210823.txt
-rw-r--r-- 1 nobody nogroup       454 Aug 23 18:07 20210824.txt
-rw-r--r-- 1 nobody nogroup 707125031 Aug 27 17:59 20210827.txt
-rw-r--r-- 1 nobody nogroup 715060012 Aug 28 17:59 20210828.txt
-rw-r--r-- 1 nobody nogroup 334848071 Aug 29 17:58 20210829.txt
-rw-r--r-- 1 nobody nogroup 299974991 Aug 30 13:01 20210830.txt

```

**Comment by eliykat** [comment]
Thanks for the report! This has been reported and fixed in #1531. A hotfix should be out soon.
