### ISSUE TITLE
`updatedb` fails with single quotes in `globalSettings__sqlServer__connectionString`

### ISSUE THREAD

**Issue by enoch85** [bitwarden/server#1638]
### Steps To Reproduce

1. Do a fresh installation of self-hosted Bitwarden
2. Enter all the credentials as you normally would
3. Wait for the error to happen

### Expected Result

Bitwarden should install normally.

### Actual Result

Since `globalSettings__sqlServer__connectionString=` have single quotes in the settings, it fails with: 

```
Unhandled exception. System.ArgumentException: Format of the initialization string does not conform to specification starting at index 194.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Bit.Migrator.DbMigrator..ctor(String connectionString, ILogger`1 logger) in /home/runner/work/server/server/util/Migrator/DbMigrator.cs:line 22
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 192
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 157
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 55
```

### Additional Context
The fix for the issue is using [double quotes instead of single quotes](https://www.reddit.com/r/Bitwarden/comments/p3gz0w/connect_to_database_with_manual_install/) in the string above.

The file in question is: `/.../bwdata/env/global.override.env`

Running `biwarden.sh updatedb` after changing to double quotes, fixed the issue.

### Build Version

1.43.0

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04
Docker
A really powerful VPS

**Comment by bmercernccer** [comment]
I just encountered this same bug, and came to report it, but here it is. Thanks.
