### ISSUE TITLE
Unable to migrate database

### ISSUE THREAD

**Issue by dan-lawrence92** [bitwarden/server#1777]
### Steps To Reproduce

1 - update to latest docker image
2 - updatedb

### Expected Result

database updated

### Actual Result

[Information] SQL exception has occured in script: '"Bit.Migrator.DbScripts.2021-07-22_00_Provider.sql"'
2021-12-20 14:33:53.971 +00:00 [Error] Script block number: 96; Block line 19; Procedure "Event_ReadPageByProviderId"; Number 207; Message: "Invalid column name 'Providerid'."
2021-12-20 14:33:53.982 +00:00 [Error] System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Providerid'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command)
   at DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)
ClientConnectionId:2f4d5af2-7eab-4874-8bbc-eb7c801e6301
Error Number:207,State:1,Class:16

### Build Version

1.45.2

### Environment

Self-Hosted

**Comment by Hinton** [comment]
Hi @dan-lawrence92,

It seems we had a typo in the migration. I've created a PR to resolve this issue. Which should be included in the next release.

Typically SQL Server is configured to use case insensitive collation which is why we haven't gotten any other reports of this issue.
