### ISSUE TITLE
Migrating database. Unhandled exception

### ISSUE THREAD

**Issue by martinorob** [bitwarden/server#1979]
### Steps To Reproduce

Migrating database.
Unhandled exception. System.ArgumentException: Format of the initialization string does not conform to specification starting at index 194.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Bit.Migrator.DbMigrator..ctor(String connectionString, ILogger`1 logger) in /home/runner/work/server/server/util/Migrator/DbMigrator.cs:line 22
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 196
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 161
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 59

### Expected Result

Migration ok

### Actual Result

Unhandled exception

### Build Version

bitwarden.sh version 1.48.1 Docker version 20.10.14, build a224086 docker-compose version 1.29.2, build 5becea4c

### Environment

Self-Hosted

### Environment Details

Ubuntu 20

**Comment by Hinton** [comment]
The connection string is malformed, most likely it's using single quotes instead of double quotes per https://github.com/bitwarden/server/issues/1546#issuecomment-914893383.

If you're still experiencing this issue and the suggestions in that Issue don't help, please contact our Customer Success team for further help. We ask that you please contact us using our contact page, here: [bitwarden.com/contact](https://bitwarden.com/contact). You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
