### ISSUE TITLE
Database Migration Failure Durring Update 

### ISSUE THREAD

**Issue by matthewschroer** [bitwarden/server#2069]
### Steps To Reproduce

run ./bitwarden updateself
run ./bitwarden update

### Expected Result

bit warden will update and come back on line with all containers healthy

### Actual Result

bitwarden fails to migrate database during update. resulting in multiple containers being unhealthy including the mssql container.

### Screenshots or Videos

bitwarden@bitwardenenc:/opt/bitwarden$ ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2022.5.2
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
docker-compose version 1.25.0, build unknown

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
2022.5.2: Pulling from bitwarden/setup
Digest: sha256:fc63bf509c518d15fe136641b19b4e605d0e267aae1999a1d92b42ba7d37c2a5
Status: Image is up to date for bitwarden/setup:2022.5.2
docker.io/bitwarden/setup:2022.5.2

Building docker environment files.
Building docker environment override files.
Building nginx config.
Building FIDO U2F app id.
Building docker-compose.yml.

Pulling mssql         ... done
Pulling web           ... done
Pulling attachments   ... done
Pulling api           ... done
Pulling identity      ... done
Pulling sso           ... done
Pulling admin         ... done
Pulling icons         ... done
Pulling notifications ... done
Pulling events        ... done
Pulling nginx         ... done
Creating network "docker_default" with the default driver
Creating network "docker_public" with the default driver
Creating bitwarden-notifications ... done
Creating bitwarden-icons         ... done
Creating bitwarden-api           ... done
Creating bitwarden-events        ... done
Creating bitwarden-sso           ... done
Creating bitwarden-attachments   ... done
Creating bitwarden-web           ... done
Creating bitwarden-identity      ... done
Creating bitwarden-mssql         ... done
Creating bitwarden-admin         ... done
Creating bitwarden-nginx         ... done
2022.5.2: Pulling from bitwarden/setup
Digest: sha256:fc63bf509c518d15fe136641b19b4e605d0e267aae1999a1d92b42ba7d37c2a5
Status: Image is up to date for bitwarden/setup:2022.5.2
docker.io/bitwarden/setup:2022.5.2

Bitwarden is up and running!
===================================================

visit https://pass.matthewschroer.com
to update, run `./bitwarden.sh updateself` and then `./bitwarden.sh update`

Total reclaimed space: 0B
Pausing 60 seconds for database to come online. Please wait...
2022.5.2: Pulling from bitwarden/setup
Digest: sha256:fc63bf509c518d15fe136641b19b4e605d0e267aae1999a1d92b42ba7d37c2a5
Status: Image is up to date for bitwarden/setup:2022.5.2
docker.io/bitwarden/setup:2022.5.2

Migrating database.
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Migrator.DbMigrator.MigrateMsSqlDatabase(Boolean enableLogging, CancellationToken cancellationToken) in /home/runner/work/server/server/util/Migrator/DbMigrator.cs:line 49
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 199
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 161
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 59
ClientConnectionId:00000000-0000-0000-0000-000000000000
bitwarden@bitwardenenc:/opt/bitwarden$ docker ps
CONTAINER ID   IMAGE                                  COMMAND            CREATED         STATUS
        PORTS                                                                                                  NAMES
4d698488b14b   bitwarden/nginx:2022.5.2               "/entrypoint.sh"   5 minutes ago   Restarting (1) 36 seconds ago                                                                                                                 bitwarden-nginx
14650aeb8650   bitwarden/admin:2022.5.2               "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)               5000/tcp                                                                                               bitwarden-admin
81fa45b09bab   bitwarden/mssql:2022.5.2               "/entrypoint.sh"   5 minutes ago   Up About a minute (health: starting)                                                                                                          bitwarden-mssql
f270e76b28ec   bitwarden/identity:2022.5.2            "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
        5000/tcp                                                                                               bitwarden-identity
b1e672b2acb6   bitwarden/attachments:2022.5.2         "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
                                                                                                               bitwarden-attachments
f0b33275ae14   bitwarden/web:2022.5.2                 "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
                                                                                                               bitwarden-web
b111d0720873   bitwarden/sso:2022.5.2                 "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)               5000/tcp                                                                                               bitwarden-sso
abee6938a50a   bitwarden/events:2022.5.2              "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
        5000/tcp                                                                                               bitwarden-events
00bc373899e5   bitwarden/notifications:2022.5.2       "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
        5000/tcp                                                                                               bitwarden-notifications
3822369a0209   bitwarden/icons:2022.5.2               "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
        5000/tcp                                                                                               bitwarden-icons
214c2c5e5bb7   bitwarden/api:2022.5.2                 "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)
        5000/tcp                                                                                               bitwarden-api
8aca5a275a89   lscr.io/linuxserver/syncthing:latest   "/init"            13 days ago     Up 8 minutes
        0.0.0.0:8384->8384/tcp, 0.0.0.0:21027->21027/udp, 0.0.0.0:22000->22000/tcp, 0.0.0.0:22000->22000/udp   syncthing
460c67835e73   containrrr/watchtower:latest           "/watchtower"      4 months ago    Up 8 minutes
        8080/tcp                                                                                               CoAgXjCDAqpGKjDsjkPivqGXbPMwZded

### Additional Context

I have restored from multiple backups and attempted clean install. 

### Build Version

2022.5.2

### Environment

Self-Hosted

### Environment Details

Running on a Ubuntu 20.04.4 virtual machine 
2 cores 
10 gigs ram
docker-compose

**Comment by matthewschroer** [comment]
Ended up migrating to fresh host and that seemed to resolve the issue
