### ISSUE TITLE
Sign in fails with "An unexpected error occurred."

### ISSUE THREAD

**Issue by MegaThorx** [bitwarden/server#2103]
### Steps To Reproduce

1. Go to bitwarden web OR app
2. Try to sign in (with correct credentials)
3. Get a beautiful error message

### Expected Result

I should be able to sign in

### Actual Result

Sign in fails with the mentioned "An unexpected error occurred." message.

### Additional Context

I checked the logs and found the following error.

The server has been recently upgraded to the latest version as mentioned in the docs (https://bitwarden.com/help/updating-on-premise/).
```
2022-07-07 15:19:55.590 +00:00 [Error] Connection id ""0HMJ0569LD0SE"", Request id ""0HMJ0569LD0SE:00000002"": An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@InstallationId', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at Bit.Infrastructure.Dapper.Repositories.Repository`2.CreateAsync(T obj) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/Repository.cs:line 55
   at Bit.Infrastructure.Dapper.Repositories.EventRepository.CreateAsync(IEvent e) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/EventRepository.cs:line 96
   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e) in /home/runner/work/server/server/src/Core/Services/Implementations/RepositoryEventWriteService.cs:line 20
   at Bit.Core.Services.EventService.LogUserEventAsync(Guid userId, EventType type, Nullable`1 date) in /home/runner/work/server/server/src/Core/Services/Implementations/EventService.cs:line 85
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildSuccessResultAsync(User user, T context, Device device, Boolean sendRememberToken) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 147
   at Bit.Core.IdentityServer.BaseRequestValidator`1.ValidateAsync(T context, ValidatedTokenRequest request) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 132
   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/runner/work/server/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 86
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, ICurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 21
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Bit.SharedWeb.Utilities.ServiceCollectionExtensions.<>c__DisplayClass12_0.<<UseDefaultMiddleware>b__1>d.MoveNext() in /home/runner/work/server/server/src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:line 502
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Bit.Identity.Startup.<>c__DisplayClass10_1.<<Configure>b__2>d.MoveNext() in /home/runner/work/server/server/src/Identity/Startup.cs:line 168
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
ClientConnectionId:840c8e9f-c19f-46db-a488-efe8428ae4a1
Error Number:201,State:4,Class:16

```

### Build Version

2022.5.2

### Environment

Self-Hosted

### Environment Details

OS: Ubuntu 22.04
Bitwarden is running in Docker

**Comment by dbosompem** [comment]
Hi @MegaThorx , sorry you're facing this issue. Can you check if your database migration applied correctly, or your containers were all updated after the DB migration?

**Comment by MegaThorx** [comment]
```
root@alpos:/docker/bitwarden# docker ps | grep bitwarden
d04fac720884   bitwarden/nginx:1.46.2             "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   80/tcp, 8080/tcp, 8443/tcp                                                                                                                                                                                                          bitwarden-nginx
bb74945dae60   bitwarden/admin:1.46.2             "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-admin
24acf61be6ac   bitwarden/mssql:1.46.2             "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)                                                                                                                                                                                                                                       bitwarden-mssql
1e8b00a7822d   bitwarden/icons:1.46.2             "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-icons
be1a6adfefd7   bitwarden/sso:1.46.2               "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-sso
6daf16c570a4   bitwarden/api:1.46.2               "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-api
3ae8b0df59d5   bitwarden/attachments:1.46.2       "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)                                                                                                                                                                                                                                       bitwarden-attachments
386de54a7c3d   bitwarden/notifications:1.46.2     "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-notifications
4fa23b5b3fc3   bitwarden/identity:1.46.2          "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-identity
30304542e522   bitwarden/web:2.26.1               "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)                                                                                                                                                                                                                                       bitwarden-web
52c23259d88a   bitwarden/events:1.46.2            "/entrypoint.sh"         14 minutes ago   Up 14 minutes (healthy)   5000/tcp                                                                                                                                                                                                                            bitwarden-events
```

Not sure on how to check this?

```
root@alpos:/docker/bitwarden# ./bitwarden.sh updatedb
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2022.5.2
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0

2022.5.2: Pulling from bitwarden/setup
Digest: sha256:fc63bf509c518d15fe136641b19b4e605d0e267aae1999a1d92b42ba7d37c2a5
Status: Image is up to date for bitwarden/setup:2022.5.2
docker.io/bitwarden/setup:2022.5.2

Migrating database.
Migration successful.
Database update complete
```

**Comment by dbosompem** [comment]
Thanks for the additional detail, please connect with our [official support team](https://bitwarden.com/contact/) for further investigation.

**Comment by gerhardmpl** [comment]
@dbosompem I have the same issue with build version 2022.5.2 (self-hosted) but on a virtualized Debian 10 (Buster, kernel 4.19.0-21.amd64) with Docker (20.10.17 build 100c701). `bitwarden/mssql` keeps restarting without success and hence `./bitwarden.sh updatedb` can not run.

**Comment by MegaThorx** [comment]
The `bitwarden/mssql` server is running as it should and the migrations should have been executed (`./bitwarden.sh updatedb` runs like it should). This is also the reason why I can still access the bitwarden server through existing sessions, but I'm unable to create new ones.

And the error message sounds more like the database call is missing the `InstallationId` parameter than the database is missing the `InstallationId` column.

I'm in contact with the support, but I didn't get a resolution yet.
