### ISSUE TITLE
Push notifiication error in log

### ISSUE THREAD

**Issue by Marx1st** [bitwarden/server#2189]
### Steps To Reproduce

1. open logs/identity/Identity/20220815.txt

### Expected Result

no errors

### Actual Result

2022-08-15 08:00:58.794 +00:00 [Error] Failed to send to "https://push.bitwarden.com/push/register".
System.Text.Json.JsonException: 'e' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Bit.Core.Services.BaseIdentityClientService.SendAsync[TRequest,TResult](HttpMethod method, String path, TRequest requestModel) in /home/runner/work/server/server/src/Core/Services/Implementations/BaseIdentityClientService.cs:line 75

### Additional Context

I was checking the logs and found this error. 

### Build Version

bitwarden.sh version 2022.6.2 Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1 docker-compose version 1.25.0, build 0a186604

### Environment

Self-Hosted

### Environment Details

- Ubuntu 20.04.4 LTS

**Comment by ryuuc** [comment]
Before `ReadFromJsonAsync` here https://github.com/bitwarden/server/blob/231eb84e694814b658cf5a52e45b782d587f97e4/src/Core/Services/Implementations/BaseIdentityClientService.cs#L71
calling  `response.EnsureSuccessStatusCode();`  to throw an exception if the http call is not successful will give us more details

**Comment by Greenderella** [comment]
Hello,

I wanted to follow up on this issue. After reviewing the details and conducting tests, it appears that the reported problem with expired or invalid authentication tokens is not currently causing any disruption of service. Additionally, I could not find any other reports or instances of this issue.

We use GitHub issues as a place to track bugs and other development related issues. If you experience any service disruptions and believe this error might be involved, please reach out to us using the “Contact support” form available on our Help Center [here](https://bitwarden.com/help/). You can include a link to this issue in your message.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
