### ISSUE TITLE
Unable to send E-Mails with the latest version

### ISSUE THREAD

**Issue by Flayckz** [bitwarden/server#2378]
### Steps To Reproduce

1. Create any account in self hosted instance
2. Verify E-Mail ( webinterface says success )

### Expected Result

E-Mail being send to destination

### Actual Result

No E-Mail Send

### Screenshots or Videos

logs/api/Api shows:

2-11-03 12:01:37.209 +00:00 [Error] Failed to send to "https://push.bitwarden.com/push/send".
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Bit.Core.Services.BaseIdentityClientService.SendAsync[TRequest,TResult](HttpMethod method, String path, TRequest requestModel) in /home/runner/work/server/server/src/Core/Services/Implementations/BaseIdentityClientService.cs:line 71

### Build Version

2022.10.0

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04.1 LTS 

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Flayckz** [comment]
Im Using a self hosted smtp server which is also being used by other apps successfully.

**Comment by rezakhan1** [comment]
Hi @Hinton  is this issue still open?

**Comment by Hinton** [comment]
@rezakhan1 I never got a reply and the log is unrelated to the error, so I'm going to close this issue.

If anyone encounters a similar issue please reach out to [support](https://bitwarden.com/contact/) and they should be able to assist in troubleshooting the configuration.
