### ISSUE TITLE
Verify Email send produces error

### ISSUE THREAD

**Issue by ajkelsey** [bitwarden/server#2647]
### Steps To Reproduce

1. Login to new account
2. Click Verify Email "Send email" button.

### Expected Result

Expected an email to be sent to account email address.

### Actual Result

Website generated an error.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/64913190/215358195-f3895ef0-6a90-4966-85f6-e52b7409da23.png)

From the Developer Console

![image](https://user-images.githubusercontent.com/64913190/215358231-cf08edf4-c7f8-4fc0-bffe-e56cba1c0133.png)

### Githash Version

"version":"2023.1.0","gitHash"

### Environment Details

Ubuntu
Docker Compose

### Database Image

mariadb:10

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Could you please share your SMTP settings? It looks like it might be misconfigured.

**Comment by ajkelsey** [comment]
```
globalSettings__mail__replyToEmail=MY EMAIL ADDRESS
globalSettings__mail__smtp__host=SMTP SERVER
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=EMAIL LOGIN
globalSettings__mail__smtp__password=EMAIL PASSWORD
```

**Comment by kspearrin** [comment]
Can you check the error logs under /etc/bitwarden/logs/api.log?

**Comment by ajkelsey** [comment]
api.log

```
2023-01-31 17:46:34.485 +00:00 [ERR] 535: Incorrect authentication data
MailKit.Security.AuthenticationException: 535: Incorrect authentication data
 ---> MailKit.Net.Smtp.SmtpCommandException: Incorrect authentication data
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /source/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 92
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /source/src/Core/Services/Implementations/HandlebarsMailService.cs:line 50
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /source/src/Core/Services/Implementations/UserService.cs:line 507
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /source/src/Api/Controllers/AccountsController.cs:line 182
   at lambda_method411(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by kspearrin** [comment]
Errors show that is cannot authenticate to your mail server for whatever reason

**Comment by ajkelsey** [comment]
Is there some way for me to get more detailed information on why it is failing? I have verified that the settings work using an email client. I have also confirmed that bitwarden is able to reach the mail server.

**Comment by ajkelsey** [comment]
Ok. I have discovered the misconfiguration in my settings. 🤦‍♂️ I am now able to send the email. However, the verification link returns a 404 page not found.

**Comment by kspearrin** [comment]
Can you paste what the verification button link is?

**Comment by ajkelsey** [comment]
I have located the configuration error and it is now working. 🤦‍♂️ I was also able to identify the problem with the verify link address. Thank you for your help and patience in getting on the right track. 👍

**Comment by robogito** [comment]
Try to uncomment all this:

BW_ENABLE_ADMIN=true
BW_ENABLE_API=true
BW_ENABLE_EVENTS=false
BW_ENABLE_ICONS=true
BW_ENABLE_IDENTITY=true
BW_ENABLE_NOTIFICATIONS=true
BW_ENABLE_SCIM=false
BW_ENABLE_SSO=false
