### ISSUE TITLE
bitwarden-sso not starting (cannot connect to database) - 2023.01

### ISSUE THREAD

**Issue by tokyovigilante** [bitwarden/server#2675]
### Steps To Reproduce

1. Install Bitwarden via script (`./bitwarden.sh install`)
2. Observe `-sso` container does not start up due to failed DB access.

### Expected Result

Bitwarden loads and is available via web and other clients.

### Actual Result

`bitwarden-sso` container fails to load, with error regarding SQL DB access. However (`-mssql`) container appears fine.

`-sso` log:

```
[Tue  3:10PM] ryan@xserve ~/docker/bitwarden/$ docker logs bitwarden-sso
info: IdentityServer4.Startup[0]
      Starting IdentityServer4 version 4.1.2+997a6cdd643e46cd5762b710c4ddc43574cbec2e
info: IdentityServer4.Startup[0]
      You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
info: IdentityServer4.Startup[0]
      Using the default authentication scheme idsrv for IdentityServer
info: Bit.Sso.Startup[12482444]
      SSO started.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/alive - -
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
      --- End of stack trace from previous location ---
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 417
         at Bit.Infrastructure.Dapper.Repositories.SsoConfigRepository.GetManyByRevisionNotBeforeDate(Nullable`1 notBefore) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/SsoConfigRepository.cs:line 50
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.LoadAllDynamicSchemesIntoCacheAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 152
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.GetRequestHandlerSchemesAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 128
         at Bit.Sso.Utilities.SsoAuthenticationMiddleware.Invoke(HttpContext context) in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/SsoAuthenticationMiddleware.cs:line 36
         at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
         at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, ICurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 19
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
      ClientConnectionId:00000000-0000-0000-0000-000000000000
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
      System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 417
         at Bit.Infrastructure.Dapper.Repositories.SsoConfigRepository.GetManyByRevisionNotBeforeDate(Nullable`1 notBefore) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/SsoConfigRepository.cs:line 50
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.LoadAllDynamicSchemesIntoCacheAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 152
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.GetRequestHandlerSchemesAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 128
         at Bit.Sso.Utilities.SsoAuthenticationMiddleware.Invoke(HttpContext context) in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/SsoAuthenticationMiddleware.cs:line 36
         at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
         at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, ICurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 19
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
      ClientConnectionId:00000000-0000-0000-0000-000000000000
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMO8M1TEF91P", Request id "0HMO8M1TEF91P:00000002": An unhandled exception was thrown by the application.
      System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
      --- End of stack trace from previous location ---
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 417
         at Bit.Infrastructure.Dapper.Repositories.SsoConfigRepository.GetManyByRevisionNotBeforeDate(Nullable`1 notBefore) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/SsoConfigRepository.cs:line 50
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.LoadAllDynamicSchemesIntoCacheAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 152
         at Bit.Core.Business.Sso.DynamicAuthenticationSchemeProvider.GetRequestHandlerSchemesAsync() in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs:line 128
         at Bit.Sso.Utilities.SsoAuthenticationMiddleware.Invoke(HttpContext context) in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/SsoAuthenticationMiddleware.cs:line 36
         at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
         at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, ICurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 19
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Bit.Sso.Startup.<>c__DisplayClass9_1.<<Configure>b__2>d.MoveNext() in /home/runner/work/server/server/bitwarden_license/src/Sso/Startup.cs:line 106
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
      ClientConnectionId:00000000-0000-0000-0000-000000000000
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/alive - - - 500 0 - 29560.1859ms
```

### Build Version

2023-01

### Environment

Self-Hosted

### Environment Details

```
bitwarden.sh version 2023.1.0
Docker version 23.0.0, build e92dd87
Docker Compose version v2.15.1
```

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tokyovigilante** [comment]
`docker ps`:

```
CONTAINER ID   IMAGE                                          COMMAND            CREATED         STATUS                       PORTS                                                                                                                                                          NAMES
f8daa8b9445c   bitwarden/nginx:2023.1.0                       "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       80/tcp, 8443/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp                                                                                                    bitwarden-nginx
af420c4b3d74   bitwarden/admin:2023.1.0                       "/entrypoint.sh"   6 minutes ago   Up 6 minutes (unhealthy)     5000/tcp                                                                                                                                                       bitwarden-admin
883fb85464b7   bitwarden/notifications:2023.1.0               "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp                                                                                                                                                       bitwarden-notifications
47737e5922c8   bitwarden/api:2023.1.0                         "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp                                                                                                                                                       bitwarden-api
b715e95f1de0   bitwarden/web:2023.1.0                         "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp                                                                                                                                                       bitwarden-web
d6132347cdeb   bitwarden/sso:2023.1.0                         "/entrypoint.sh"   6 minutes ago   Up 6 minutes (unhealthy)     5000/tcp                                                                                                                                                       bitwarden-sso
2fc4cf250f97   bitwarden/mssql:2023.1.0                       "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)                                                                                                                                                                      bitwarden-mssql
c3801960e471   bitwarden/attachments:2023.1.0                 "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)                                                                                                                                                                      bitwarden-attachments
e84581d261e4   bitwarden/events:2023.1.0                      "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp                                                                                                                                                       bitwarden-events
c3610bda30b1   bitwarden/icons:2023.1.0                       "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp                                                                                                                                                       bitwarden-icons
afae72593c7a   bitwarden/identity:2023.1.0                    "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)       5000/tcp   
```
`docker logs bitwarden-mssql`:
```
2023-02-07 02:10:00.16 Server      The licensing PID was successfully processed. The new edition is [Express Edition].
2023-02-07 02:10:00.45 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2023-02-07 02:10:00.46 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2023-02-07 02:10:00.46 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2023-02-07 02:10:00.48 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2023-02-07 02:10:00.78 Server      Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)
	Jul 22 2022 12:11:33
	Copyright (C) 2019 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 20.04.4 LTS) <X64>
2023-02-07 02:10:00.78 Server      UTC adjustment: 0:00
2023-02-07 02:10:00.79 Server      (c) Microsoft Corporation.
2023-02-07 02:10:00.79 Server      All rights reserved.
2023-02-07 02:10:00.79 Server      Server process ID is 380.
2023-02-07 02:10:00.79 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2023-02-07 02:10:00.79 Server      Registry startup parameters:
	 -d /var/opt/mssql/data/master.mdf
	 -l /var/opt/mssql/data/mastlog.ldf
	 -e /var/opt/mssql/log/errorlog
2023-02-07 02:10:00.80 Server      SQL Server detected 1 sockets with 4 cores per socket and 8 logical processors per socket, 8 total logical processors; using 8 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2023-02-07 02:10:00.80 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2023-02-07 02:10:00.80 Server      Detected 25563 MB of RAM. This is an informational message; no user action is required.
2023-02-07 02:10:00.81 Server      Using conventional memory in the memory manager.
2023-02-07 02:10:00.81 Server      Page exclusion bitmap is enabled.
2023-02-07 02:10:00.86 Server      Buffer pool extension is not supported on Linux platform.
2023-02-07 02:10:00.86 Server      Buffer Pool: Allocating 4194304 bytes for 3993600 hashPages.
2023-02-07 02:10:01.01 Server      Buffer pool extension is already disabled. No action is necessary.
2023-02-07 02:10:01.30 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2023-02-07 02:10:01.32 Server      Query Store settings initialized with enabled = 1,
2023-02-07 02:10:01.34 Server      The maximum number of dedicated administrator connections for this instance is '1'
2023-02-07 02:10:01.35 Server      Node configuration: node 0: CPU mask: 0x00000000000000ff:0 Active CPU mask: 0x00000000000000ff:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2023-02-07 02:10:01.41 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2023-02-07 02:10:01.42 Server      In-Memory OLTP initialized on standard machine.
2023-02-07 02:10:01.49 Server      [INFO] Created Extended Events session 'hkenginexesession'
2023-02-07 02:10:01.49 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
ForceFlush is enabled for this instance.
2023-02-07 02:10:01.50 Server      Total Log Writer threads: 2. This is an informational message; no user action is required.
2023-02-07 02:10:01.51 Server      CLR version v4.0.30319 loaded.
2023-02-07 02:10:01.52 Server      clflush is selected for pmem flush operation.
2023-02-07 02:10:01.52 Server      Software Usage Metrics is disabled.
2023-02-07 02:10:01.53 spid10s     [1]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-02-07 02:10:01.53 spid10s     Starting up database 'master'.
ForceFlush feature is enabled for log durability.
2023-02-07 02:10:01.61 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [1] name [master]
2023-02-07 02:10:01.61 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [1] name [master]
2023-02-07 02:10:01.79 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [1] name [master]
2023-02-07 02:10:01.80 spid10s     Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2023-02-07 02:10:01.80 spid10s     An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.
2023-02-07 02:10:01.82 spid10s     SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2023-02-07 02:10:01.83 spid10s     SQL Server Audit has started the audits. This is an informational message. No user action is required.
2023-02-07 02:10:01.90 spid10s     SQL Trace ID 1 was started by login "sa".
2023-02-07 02:10:01.98 spid10s     Server name is '94d76b41fa65'. This is an informational message only. No user action is required.
2023-02-07 02:10:02.00 Server      Common language runtime (CLR) functionality initialized.
2023-02-07 02:10:02.02 spid23s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
2023-02-07 02:10:02.02 spid10s     [4]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-02-07 02:10:02.02 spid23s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
2023-02-07 02:10:02.02 spid12s     [32767]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-02-07 02:10:02.02 spid10s     Starting up database 'msdb'.
2023-02-07 02:10:02.03 spid12s     Starting up database 'mssqlsystemresource'.
2023-02-07 02:10:02.04 spid12s     The resource database build version is 15.00.4249. This is an informational message only. No user action is required.
2023-02-07 02:10:02.06 spid12s     [3]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-02-07 02:10:02.07 spid12s     Starting up database 'model'.
2023-02-07 02:10:02.07 spid22s     A self-generated certificate was successfully loaded for encryption.
2023-02-07 02:10:02.08 spid22s     Server is listening on [ 'any' <ipv6> 1433].
2023-02-07 02:10:02.08 spid22s     Server is listening on [ 'any' <ipv4> 1433].
2023-02-07 02:10:02.08 spid22s     Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required.
2023-02-07 02:10:02.09 spid22s     Server is listening on [ ::1 <ipv6> 1431].
2023-02-07 02:10:02.10 spid22s     Server is listening on [ 127.0.0.1 <ipv4> 1431].
2023-02-07 02:10:02.10 spid22s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2023-02-07 02:10:02.12 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [4] name [msdb]
2023-02-07 02:10:02.13 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [4] name [msdb]
2023-02-07 02:10:02.14 spid10s     RecoveryUnit::InitPersistentVersionStore failed with db [4] name [msdb]
2023-02-07 02:10:02.18 spid12s     Clearing tempdb database.
2023-02-07 02:10:02.39 spid12s     [2]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-02-07 02:10:02.39 spid12s     Starting up database 'tempdb'.
2023-02-07 02:10:02.55 spid23s     The Service Broker endpoint is in disabled or stopped state.
2023-02-07 02:10:02.55 spid23s     The Database Mirroring endpoint is in disabled or stopped state.
2023-02-07 02:10:02.56 spid23s     Service Broker manager has started.
2023-02-07 02:10:02.56 spid10s     Recovery is complete. This is an informational message only. No user action is required.
````

**Comment by SergeantConfused** [comment]
Hi @tokyovigilante,

I attempted to reproduce your issue and was unable to do so. I think this could be related to your particular setup and environment; Could you please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ ? You can include a link to this issue in the message content.

I say that because we use GitHub issues as a place to track bugs and other development related issues. 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thank you.
