### ISSUE TITLE
Strange behavior since 2023.2.0 upgrade - unhandled error has occured

### ISSUE THREAD

**Issue by EgonHeuson** [bitwarden/server#2738]
### Steps To Reproduce

Hey!
We've deployed since few month 2 self-hosted Bitwarden instances on our server. We had no issues until early this week when we tried to add new users to one of it. When filling up the account creation form, it returned a "an unhandled error has occured" message. 

<img width="300" alt="2023-02-23_18-42-03" src="https://user-images.githubusercontent.com/32910291/220987252-458d7672-5311-47c8-b8d2-a21a2a63d4da.png">

Here are the logs of the identity container:
`2023-02-23T17:42:17.178042509Z warn: Bit.Identity.IdentityServer.ResourceOwnerPasswordValidator[12482444]
2023-02-23T17:42:17.178164591Z       => SpanId:d120e1af1cd85111, TraceId:2052f79fb44519590bf1325aa81772da, ParentId:0000000000000000 => ConnectionId:0HMOLOIFFH934 => RequestPath:/identity/connect/token RequestId:0HMOLOIFFH934:00000002
2023-02-23T17:42:17.178183310Z       Failed login attempt. 172.21.0.10
2023-02-23T17:42:58.624841279Z fail: Bit.SharedWeb.Utilities.ExceptionHandlerFilterAttribute[0]
2023-02-23T17:42:58.624984440Z       => SpanId:bd4c4c957b04ef07, TraceId:87fa1acabbec5b6602ba44d9050a9751, ParentId:0000000000000000 => ConnectionId:0HMOLOIFFH937 => RequestPath:/identity/accounts/register RequestId:0HMOLOIFFH937:00000002 => Bit.Identity.Controllers.AccountsController.PostRegister (Identity)
2023-02-23T17:42:58.624996857Z       Resource temporarily unavailable
2023-02-23T17:42:58.625056929Z       System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
2023-02-23T17:42:58.625066020Z          at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
2023-02-23T17:42:58.625155627Z          at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
2023-02-23T17:42:58.625165748Z          at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
2023-02-23T17:42:58.625171570Z          at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
2023-02-23T17:42:58.625228500Z          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-02-23T17:42:58.625263872Z       --- End of stack trace from previous location ---
2023-02-23T17:42:58.625339419Z          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-02-23T17:42:58.625357159Z       --- End of stack trace from previous location ---
2023-02-23T17:42:58.625363767Z          at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
2023-02-23T17:42:58.625420004Z          at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
2023-02-23T17:42:58.625499076Z          at MailKit.MailService.ConnectNetwork(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
2023-02-23T17:42:58.625508379Z          at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
2023-02-23T17:42:58.625566511Z          at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/runner/work/server/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 86
2023-02-23T17:42:58.625646286Z          at Bit.Core.Services.HandlebarsMailService.SendWelcomeEmailAsync(User user) in /home/runner/work/server/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 271
2023-02-23T17:42:58.625705363Z          at Bit.Core.Services.UserService.RegisterUserAsync(User user, String masterPassword, String token, Nullable`1 orgUserId) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 313
2023-02-23T17:42:58.625714283Z          at Bit.Identity.Controllers.AccountsController.PostRegister(RegisterRequestModel model) in /home/runner/work/server/server/src/Identity/Controllers/AccountsController.cs:line 41
2023-02-23T17:42:58.625790435Z          at lambda_method17(Closure , Object )
2023-02-23T17:42:58.625799423Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-02-23T17:42:58.625855859Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
2023-02-23T17:42:58.625935991Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-02-23T17:42:58.625945638Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-02-23T17:42:58.626001063Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-02-23T17:42:58.626081231Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-02-23T17:42:58.626161549Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

Also very strange, if we try to create again the user account, it says that the email is already in use like if it was correctly created the first time.

We then logged in and tried to send emails with the connected account but the same error happens and no email is sent. We then tried to connect to the admin panel, and here nothing happens after we enter the admin email and ask the application to generate the token link, until the page reloads onto a 404 error.

Even more weird, while we can still connect to our existing accounts from our work computers, if we try from other ones, it doesn't succeed to connect and we also get the "unhandled error".

Also I noticed that the icon container is taking quite a long time to start, and goes through an "unhealthy" state before coming back to a "healthy" state. are are the logs:

`warn: Bit.Icons.Services.IIconFetchingService[0]
      => SpanId:4a984affed715fe4, TraceId:8b0525e9a8655a0f1b6f85c5835934a8, ParentId:0000000000000000 => ConnectionId:0HMOLOIG6EFTB => RequestPath:/google.com/icon.png RequestId:0HMOLOIG6EFTB:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Couldn't load a website for google.com: null.
warn: Bit.Icons.Controllers.IconsController[0]
      => SpanId:4a984affed715fe4, TraceId:8b0525e9a8655a0f1b6f85c5835934a8, ParentId:0000000000000000 => ConnectionId:0HMOLOIG6EFTB => RequestPath:/google.com/icon.png RequestId:0HMOLOIG6EFTB:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Null result returned for google.com.
warn: Bit.Icons.Services.IIconFetchingService[0]
      => SpanId:2b3d96e10a1f6d48, TraceId:d58b500cc6ac43f9d2932a28c622aebd, ParentId:0000000000000000 => ConnectionId:0HMOLOIG6EFTC => RequestPath:/google.com/icon.png RequestId:0HMOLOIG6EFTC:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Couldn't load a website for google.com: null.
warn: Bit.Icons.Controllers.IconsController[0]
      => SpanId:2b3d96e10a1f6d48, TraceId:d58b500cc6ac43f9d2932a28c622aebd, ParentId:0000000000000000 => ConnectionId:0HMOLOIG6EFTC => RequestPath:/google.com/icon.png RequestId:0HMOLOIG6EFTC:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Null result returned for google.com.
`

I tried to reinstall bitwarden and now I get the same issue with the new instance like if it was keeping some hidden files somewhere that make the new config wrong. Also, even worse, if I create a new virtual machine, these issues are not present anymore on a fresh or reinstalled bitwarden... This is driving me crazy... :-( Any idea would be of great help! Upgrading to 2023.2.1 didn't solve the issue though... 

Also, in the logs it says "Failed login attempt. 172.21.0.10". This IP address is part of the docker_default network created by bitwarden, but doesn't correspond to any container or machine... 

### Expected Result

To work ☺️

### Actual Result

No way to create new users, or log in from other computers or log into the admin panel

### Build Version

2023.2.0

### Environment

Self-Hosted

### Environment Details

- Debian 11.6
- Intel based machine
- Docker install

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. Could you please reach out to us so we can continue troubleshooting and look further into your log files: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
