### ISSUE TITLE
Cant connect to MSSQL server: "Unhandled exception. System.Exception: Database provider type SqlServer was selected but no connection string was found."

### ISSUE THREAD

**Issue by fabioteixei** [bitwarden/server#2812]
### Steps To Reproduce

1. Deploy Bitwarden Unified container using Docker Compose and configure it to use an MSSQL DB
2. Start the docker container

### Expected Result

Bitwarden Unified being capable to connect to the MSSQL Database server.

### Actual Result

An connection error on the admin.log, api.log and identity.log:

`Unhandled exception. System.Exception: Database provider type SqlServer was selected but no connection string was found.
   at EntityFrameworkServiceCollectionExtensions.SetupEntityFramework(IServiceCollection services, String connectionString, SupportedDatabaseProviders provider) in /source/src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs:line 18
   at Bit.SharedWeb.Utilities.ServiceCollectionExtensions.AddDatabaseRepositories(IServiceCollection services, GlobalSettings globalSettings) in /source/src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:line 87
   at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /source/src/Identity/Startup.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bit.Identity.Program.Main(String[] args) in /source/src/Identity/Program.cs:line 10`

All the log files mentionend shows this same error.

### Additional Context

Here is my Docker Composer YML:

`---
version: "3.8"

services:
  bitwarden:
    container_name: "bitwarden"
    depends_on:
      - mssql
    #links:
      #- mysql
      #- mssql
    environment:
      - PUID=1000
      - PGID=1000
      - BW_DOMAIN=btw.domain.com.br
      - "globalSettings__mssql__connectionString=server=192.168.X.X;port=1433;database=bitwarden_vault;user=bitwarden;password=xxxxxxx"
      - "BW_DB_PROVIDER=mssql"
      #- "BW_DB_SERVER=192.168.2.10" #your SQL IP address or name
      #- "BW_DB_PORT=1433" #enter the SQL port that the instance is running on
      #- "BW_DB_DATABASE=bitwarden_vault"
      #- "BW_DB_USERNAME=SA"
      #- "BW_DB_PASSWORD=XXXX"
      - "BW_INSTALLATION_ID=XXXXXXXX"
      - "BW_INSTALLATION_KEY=XXXXXXX"
      - "adminSettings__admins=XX@XX"
      - "globalSettings__mail__replyToEmail=XX@XX"
      - "globalSettings__mail__smtp__host=smtp.office365.com"
      - "globalSettings__mail__smtp__port=587"
      - "globalSettings__mail__smtp__ssl=true"
      - "globalSettings__mail__smtp__username=XX@XX"
      - "globalSettings__mail__smtp__password=XXXXX"
      - "globalSettings__disableUserRegistration=false"      
    #env_file:
      #- settings.env
    image: bitwarden/self-host:beta
    restart: always
    ports:
      - "8083:8080"
      - "8444:8443"
    volumes:
      - /docker/bitwarden:/etc/bitwarden
    networks:
      - proxy
    labels:
      - "traefik.enable=true"   
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pwd.entrypoints=http"
      - "traefik.http.routers.pwd.rule=Host(`bwd.domain.com.br`)"
      - "traefik.http.middlewares.pwd-https-redirect.redirectscheme.scheme=https"      
      - "traefik.http.routers.pwd-secure.entrypoints=https"
      - "traefik.http.routers.pwd-secure.rule=Host(`bwd.domain.com.br`)"
      - "traefik.http.routers.pwd-secure.tls=true"
      - "traefik.http.routers.pwd-secure.service=pwd"
      - "traefik.http.services.pwd.loadbalancer.server.port=8080"      
      - "traefik.http.routers.pwd.middlewares=pwd-https-redirect"
  
  mssql:
    container_name: "mssql"
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - SA_PASSWORD=XXXXXX
      - ACCEPT_EULA=Y
    volumes:
      - /docker/mssql/data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - proxy

networks:
  proxy:
    external: true	  `

Its not an connectivity issue with the MSSQL DB, i can connect to the DB from my machine using the Management Studio, create the Database and the user to bitwarden juste fine.

### Githash Version

N/A

### Environment Details

- OS: Ubuntu Linux  22.04
-  Enviroment: Docker

### Database Image

mssql:2022

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by fabioteixei** [comment]
Ok, i fixed the issue. i was using the wrong database type. I was using mssql and for Microsoft SQL the right one ins sqlserver. 

Thanks all and sorry to bother.
