### ISSUE TITLE
SelfHosted SMTP Email Sending Error

### ISSUE THREAD

**Issue by Shkrelic** [bitwarden/server#2828]
### Steps To Reproduce

1. Install bitwarden self-hosted on Linux.
2. Utilize self-hosted SMTP MTA with valid certificates and TLS enabled.
3. Input the IP in the global.over.env file under globalSettings__mail__smtp__host=
3a. Alternatively, inputting the fqdn in the global.over.env file under globalSettings__mail__smtp__host=
4. Server fails to send emails securely with both IP or FQDN.

### Expected Result

Upon user creation and verification, smtp server certificates are verified and emails should be sent to user.

### Actual Result

Server produces the following error which is a known issue (API log): 

2023-03-29 12:51:26.661 +00:00 [Error] An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/runner/work/server/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 86
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /home/runner/work/server/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 50
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 513
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /home/runner/work/server/server/src/Api/Controllers/AccountsController.cs:line 182
   at lambda_method42(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Additional Context

I have **RESOLVED** the server certificate issue by adding the following entry to the end of my api container on the docker-compose.yml:

    extra_hosts:
      - "mail.server.fqdn:192.168.0.2"

### Build Version

bitwarden.sh version 2023.2.1

### Environment

Self-Hosted

### Environment Details

-OS: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
-Hardware: ProxMox VM
system     Standard PC (i440FX + PIIX, 1996)
bus        Motherboard
memory     96KiB BIOS
processor  Common KVM processor
memory     4GiB System Memory
memory     4GiB DIMM RAM

Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.16.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sso-bitwarden** [comment]
Hi,

The error message is clear, there is something wrong with the SSL cert you installed on the SMTP server.

To blindly trust the certificate, you can use the variable below in global.override.env. (restart the server after that)
globalSettings__mail__smtp__trustServer=true

But it's not recommended to do it on a production server. Should be fine for personal use.

**Comment by Shkrelic** [comment]
Hi,

I'm not sure if you saw, but this issue was **RESOLVED** securely by adding the the following entry to the docker-compose.yml:

extra_hosts:
  - "mail.server.fqdn:192.168.0.2"

I did **NOT** want to blindly trust the server. I had already tried that variable and it did in fact work, however, adding the extra_hosts entry to the compose file allows the host to properly resolve the certificate hostname to the IP and match to the certificate. I understand this may not be an issue for more complex setups, but I do not believe allowing blind trust in an environment like this should never be encouraged.

**Comment by joshtrichards** [comment]
Glad to hear you were able to troubleshoot and figure out a solution that works for you in your environment.

I'm just an observer, but the only reason this issue came up seems to be that your environment lacks a functioning DNS entry for `mail.server.fqdn` - which is the missing step for reproducing.

No DNS entry for your MTA would certainly cause a certificate check to fail!

Using Docker's `extra_hosts` I suppose is one way of working around that -  if you don't want to simply add your SMTP MTA hostname to DNS for whatever reason (nothing wrong with that).

However, a functioning DNS is sort of a reasonable expectation on the apps part. So this seems like it's a local environment config issue and it doesn't sound like a BW bug at all. The error message given was accurate. :-)

I suspect most folks running their own MTA are probably savvy enough to understand the quirks of their internal environment enough to work out the issues (as you did). So not seeing much if anything BW can or should do on their side.

Am I missing something?

**Comment by Shkrelic** [comment]
Nope. I just wanted to document this as a secure work around rather than blindly trusting the host.
