### ISSUE TITLE
API: collections/details not working, Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by domdev-p** [bitwarden/server#3031]
### Steps To Reproduce

Yesterday we upgraded from Version 1.49 to 2023.5.0

1. Go to Organizations
2. The Vault is not loading. An infinite spinning wheel shows.

https://XXXXXX/api/organizations/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/collections/details
Returns a 500 error:
```
{
    "message": "An unhandled server error has occurred.",
    "validationErrors": null,
    "exceptionMessage": null,
    "exceptionStackTrace": null,
    "innerExceptionMessage": null,
    "object": "error"
}
```
https://XXXXXX/api/organizations/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/collections
Is working as expected.

The Errorlog shows this:
```
[Error] Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at Bit.Api.Controllers.CollectionsController.CanViewCollectionAsync(String orgId, String collectionId) in /home/runner/work/server/server/src/Api/Controllers/CollectionsController.cs:line 269
   at Bit.Api.Controllers.CollectionsController.Get(String orgId, String id) in /home/runner/work/server/server/src/Api/Controllers/CollectionsController.cs:line 48
   at lambda_method97(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
```

### Expected Result

A working organization vault.

/api/organizations/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/collections/details should return a http status 200

### Actual Result

![grafik](https://github.com/bitwarden/server/assets/137295192/7779d21e-6aea-4175-befe-1c7345d58346)

### Additional Context

Database migration info:
Converting database 'master' from version 869 to the current version 904.

### Build Version

2023.5.0

### Environment

Self-Hosted

### Environment Details

- Operating System: Ubuntu
- Docker
- vCPU: 2 (Intel) RAM: 8 GB

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hi @domdev-p 

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
