### ISSUE TITLE
MSSQL Database not available.

### ISSUE THREAD

**Issue by adpur** [bitwarden/server#3075]
### Steps To Reproduce

1. bitwarden.sh install
2. edit global env for smtp
3. bitwarden updatedb
4. bitwarden.sh restart
5. error

### Expected Result

Server is running

### Actual Result

Admin never starts and fails:

ClientConnectionId:00000000-0000-0000-0000-000000000000
2023-07-06 15:15:29.445 +00:00 [Information] Finished job "DeleteSendsJob" at 07/06/2023 15:15:29.
2023-07-06 15:15:42.927 +00:00 [Error] Database unavailable for migration. Trying again (attempt #4)...
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Bit.Migrator.SqlServerDbMigrator.MigrateDatabase(Boolean enableLogging, CancellationToken cancellationToken) in /home/runner/work/server/server/util/Migrator/SqlServerDbMigrator.cs:line 49
   at Bit.Admin.HostedServices.DatabaseMigrationHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/server/server/src/Admin/HostedServices/DatabaseMigrationHostedService.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000

### Additional Context

CONTAINER ID   IMAGE                              COMMAND            CREATED         STATUS                     PORTS                                                                                    NAMES
80ce9a0e14f8   bitwarden/nginx:2023.5.1           "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   bitwarden-nginx
6f91feaef086   bitwarden/admin:2023.5.1           "/entrypoint.sh"   6 minutes ago   Up 6 minutes (unhealthy)   5000/tcp                                                                                 bitwarden-admin
e163198c0b9c   bitwarden/icons:2023.5.1           "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     5000/tcp                                                                                 bitwarden-icons
27aed0887ee6   bitwarden/sso:2023.5.1             "/entrypoint.sh"   6 minutes ago   Up 6 minutes (unhealthy)   5000/tcp                                                                                 bitwarden-sso
224aa43004f5   bitwarden/mssql:2023.5.1           "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)                                                                                              bitwarden-mssql
660d79025ce3   bitwarden/notifications:2023.5.1   "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     5000/tcp                                                                                 bitwarden-notifications
6a3ec385a4b0   bitwarden/events:2023.5.1          "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     5000/tcp                                                                                 bitwarden-events
7172049f6b58   bitwarden/identity:2023.5.1        "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     5000/tcp                                                                                 bitwarden-identity
5b0dbd50033c   bitwarden/api:2023.5.1             "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)     5000/tcp                                                                                 bitwarden-api
1a64af15431e   bitwarden/attachments:2023.5.1     "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)                                                                                              bitwarden-attachments
d73f1d3c4bf6   bitwarden/web:2023.5.1             "/entrypoint.sh"   6 minutes ago   Up 6 minutes (healthy)                                                                                              bitwarden-web

### Build Version

2023.5.1

### Environment

Self-Hosted

### Environment Details

Redhat linux 9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
