### ISSUE TITLE
[Unified] Error pre-validating against SSO service

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [bitwarden/server#3205]
### Steps To Reproduce

1. Follow the tutorial on https://bitwarden.com/help/saml-keycloak/ (Needs updating)
2. Open incognito/private window
3. Try to login via SSO

### Expected Result

Should redirect to Keycloak for authentication and redirect back (I'm kerberos enabled)

### Actual Result

Red error box pops up on screen saying **Error pre-validating against SSO service**.

Loading spinner keeps spinning.

### Screenshots or Videos

![image](https://github.com/bitwarden/server/assets/118213587/83fa455a-ede9-4795-94c9-facb31784085)

### Additional Context

Logs from docker:

fail: Bit.Identity.Controllers.SsoController[0]
      => SpanId:5f02e6c46dc1eb02, TraceId:fd52673c93ea7b154b0fe56161b4ab48, ParentId:0000000000000000 => ConnectionId:0HMSU72UBRP6A => RequestPath:/identity/account/prevalidate RequestId:0HMSU72UBRP6A:00000002 => Bit.Identity.Controllers.SsoController.PreValidate (Identity)
      Error pre-validating against SSO service
      System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5007)
       ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Bit.Identity.Controllers.SsoController.PreValidate(String domainHint) in /source/src/Identity/Controllers/SsoController.cs:line 59

### Githash Version

9b007586-dirty

### Environment Details

- Server Type: VPS (Vultr)
- vCPU/s: 1 vCPU
- RAM: 2048.00 MB
- Storage: 50 GB NVMe 
- IPv4 Address: True
- IPv6 Address: True
- Operating System: Fedora 38 Minimal (No GUI)
- Container: Docker (Standalone)
- Firewall: CSF Firewall
- DNS Resolver: Unbound
- Additional Software: Grafana Agent (Logging & Monitoring)

### Database Image

Seperate VPS same specs as Environment Details without Docker
PostgreSQL version 15.1-2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Entrepreneur-AJ** [comment]
As a note this instance is not yet in use still trying to setup so it's safe to play around with that and keycloak if need be

**Comment by trmartin4** [comment]
We are marking this issue as closed, as we cannot reproduce it internally on the latest Unified version.
