### ISSUE TITLE
self-hosted server containers update to 2024.2.2 hoses vaults

### ISSUE THREAD

**Issue by valerioa** [bitwarden/server#3849]
### Steps To Reproduce

I run a self-hosted server from containers. 
Update via
`bitwarden.sh update `
to last release
connect via web or browser app
User vaults are empty. 

### Expected Result

User vaults should be available after update

### Actual Result

it seems that something is happening with asp.net 
I tried the update several times - I have often seen this error
`The key {3943d9ce-1716-4c67-bfb4-08efe5a54371} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning`

for future internet navigators, there is a path to recovery by downgrading all containers to 2024.1.2

### Build Version

2024.2.2

### Environment

Self-Hosted

### Environment Details

- Ubuntu 22.04
- Docker containers
- cpu: 13th Gen Intel(R) Core(TM) i5-13600KF, 64Gb RAM

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by valerioa** [comment]
I reproduce dit for a total of 4 times. I recovered by downgrading to 2024.1.2. Restored db from mssql backup. Installed 2024.2.2 with bitwarden.sh update and it happened every time. Maybe computers are not so deterministic as we think.

**Comment by valerioa** [comment]
For future googlers:  the issue I have found is that, no matter how I install 2023.2.2 - there is always an error indicting that there are keys missing from the keyring

```
2024-02-29 16:33:23.667 +00:00 [Error] The key {36b874a6-a32a-4952-b1c1-df733d246614} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
System.Security.Cryptography.CryptographicException: The key {36b874a6-a32a-4952-b1c1-df733d246614} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Bit.Infrastructure.Dapper.Repositories.UserRepository.UnprotectData(User user) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/UserRepository.cs:line 302
   at Bit.Infrastructure.Dapper.Repositories.UserRepository.GetByIdAsync(Guid id) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/UserRepository.cs:line 33
   at Bit.Core.Services.UserService.GetUserByIdAsync(Guid userId) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 170
   at Bit.Core.Services.UserService.GetUserByPrincipalAsync(ClaimsPrincipal principal) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 182
   at Bit.Api.Vault.Controllers.SyncController.Get(Boolean excludeDomains) in /home/runner/work/server/server/src/Api/Vault/Controllers/SyncController.cs:line 68
   at lambda_method47(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```
