### ISSUE TITLE
2024.4.2: System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.

### ISSUE THREAD

**Issue by tmknight** [bitwarden/server#4059]
### Steps To Reproduce

self-hosted, but this appears to be related to the PR to remove the deprecated `version` attribute from the compose files:
1. version 2024.4.1
2. bitwarden.sh updateself
3. bitwarden update

### Expected Result

All containers start

### Actual Result

Status: Image is up to date for bitwarden/setup:2024.4.2
docker.io/bitwarden/setup:2024.4.2

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.PrintEnvironment() in /home/runner/work/server/server/util/Setup/Program.cs:line 169
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 61

### Build Version

2024.4.2

### Environment

Self-Hosted

### Environment Details

Linux
docker

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xiconfjs** [comment]
same problem here. Any progress on creating a workaround? Or is there a way to do a fallback?

**Comment by tmknight** [comment]
You can replace bitwarden.sh with the one from 2024.4.1 release

**Comment by xiconfjs** [comment]
Ok, workaround is to switch back to version 2024.4.1:

1. Stop bitwarden `./bitwarden.sh stop`
2. Then change the version to 2024.4.1. Patch:
```
--- bitwarden.sh_old	2024-05-07 00:45:13.804462923 +0200
+++ bitwarden.sh	2024-05-07 00:44:22.369781760 +0200
@@ -62,8 +62,8 @@
 RUN_SCRIPT_URL="https://func.bitwarden.com/api/dl/?app=self-host&platform=linux&variant=run"

 # Please do not create pull requests modifying the version numbers.
-COREVERSION="2024.4.2"
-WEBVERSION="2024.4.2"
+COREVERSION="2024.4.1"
+WEBVERSION="2024.4.1"
 KEYCONNECTORVERSION="2024.4.0"

 echo "bitwarden.sh version $COREVERSION" 
```
3. Start bitwarden again `./bitwarden.sh start`

**Comment by flotteur** [comment]
> Ok, workaround is to switch back to version 2024.4.1:
> 
>     1. Stop bitwarden `./bitwarden.sh stop`
> 
>     2. Then change the version to 2024.4.1. Patch:
> 
> 
> ```
> --- bitwarden.sh_old	2024-05-07 00:45:13.804462923 +0200
> +++ bitwarden.sh	2024-05-07 00:44:22.369781760 +0200
> @@ -62,8 +62,8 @@
>  RUN_SCRIPT_URL="https://func.bitwarden.com/api/dl/?app=self-host&platform=linux&variant=run"
> 
>  # Please do not create pull requests modifying the version numbers.
> -COREVERSION="2024.4.2"
> -WEBVERSION="2024.4.2"
> +COREVERSION="2024.4.1"
> +WEBVERSION="2024.4.1"
>  KEYCONNECTORVERSION="2024.4.0"
> 
>  echo "bitwarden.sh version $COREVERSION" 
> ```
> 
>     3. Start bitwarden again `./bitwarden.sh start`

I confirm that a rollback this way worked fine.

Thank you!

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by lengran** [comment]
I'm having this issue when upgrading. I tried to upgrade the docker but that didn't make any difference. I have reverted the script back to 2024.4.1 temporarily for now. Hope this problem will be fixed soon.

**Comment by npodbielski** [comment]
I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. 
Also after update finished this property is gone from config so this should be only one-time workaround.

**Comment by GuillaumeHullin** [comment]
For me the "workaround" was to simply start manually the containers... I still have the errors but Bitwarden is running.
```sh
sudo -u bitwarden /srv/bitwarden/bitwarden.sh start
```

**Comment by CodingMinds** [comment]
> For me the "workaround" was to simply start manually the containers... I still have the errors but Bitwarden is running.
> 
> ```shell
> sudo -u bitwarden /srv/bitwarden/bitwarden.sh start
> ```

I've tried that also, didn't help :(

**Comment by GuillaumeHullin** [comment]
> > For me the "workaround" was to simply start manually the containers... I still have the errors but Bitwarden is running.
> > ```shell
> > sudo -u bitwarden /srv/bitwarden/bitwarden.sh start
> > ```
> 
> I've tried that also, didn't help :(

What error do you get?

**Comment by CodingMinds** [comment]
> > > For me the "workaround" was to simply start manually the containers... I still have the errors but Bitwarden is running.
> > > ```shell
> > > sudo -u bitwarden /srv/bitwarden/bitwarden.sh start
> > > ```
> > 
> > 
> > I've tried that also, didn't help :(
> 
> What error do you get?

The same as in the OP IIRC. Already did a rollback to the previous version, so can't retry it.

**Comment by nex84** [comment]
> > > > For me the "workaround" was to simply start manually the containers... I still have the errors but Bitwarden is running.
> > > > ```shell
> > > > sudo -u bitwarden /srv/bitwarden/bitwarden.sh start
> > > > ```
> > > 
> > > 
> > > I've tried that also, didn't help :(
> > 
> > 
> > What error do you get?
> 
> The same as in the OP IIRC. Already did a rollback to the previous version, so can't retry it.

You can retry after running the following:
```
./bitwarden.sh updateself
```
This will gather again the new version of the bitwarden.sh script with the faulty versions.

**Comment by GuillaumeHullin** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Tested this method successfully!

**Comment by luismiparra** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

It works for me! Thanks!!

**Comment by benlenau** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Works!

**Comment by manilx** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Works!

**Comment by tmknight** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

I suggest this is the workaround and not the solution (well done, nonetheless).  `config.yml` is auto-generated by other code at runtime, so that code needs to be corrected.  Unfortunately, my C# isn't the sharpest (pun) and not finding the exact line that is the culprit.  I presume this will be fixed in short order as next release.

**Comment by tmknight** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Well spotted!  I searched the code for `compose_version` and nothing came up....well done.

**Comment by npodbielski** [comment]
@tmknight I am not sure where you comment go (did you deleted it?) but:
> I suggest this is the workaround and not the solution
I did not stated it is the solution. But a way to just ignore this if anyone had a problem get along with their life. I am sure people here have better things to do :)
>  Unfortunately, my C# isn't the sharpest (pun) and not finding the exact line that is the culprit.
They just removed a prop from whatever class it was serializing config.yaml into. Can not find property and runtime just blows up. No secret there. Probably just someone forgot to test on previous version of the config. Or just a mistake - shit happens. 
Anyway if this work it works. Yeah should be fixed but you know... one problem less out of your head :)

**Comment by Snafu** [comment]
I guess this is the culprit, I don't see any code changes that would cause it https://github.com/aaubry/YamlDotNet/issues/611

**Comment by Snafu** [comment]
> They just removed a prop from whatever class it was serializing config.yaml into. Can not find property and runtime just blows up. No secret there. Probably just someone forgot to test on previous version of the config. Or just a mistake - shit happens.
> Anyway if this work it works. Yeah should be fixed but you know... one problem less out of your head :)

Yup, this seems to be the culprit https://github.com/bitwarden/server/pull/3972/files
Obviously there is a regression testing issue though, this should never have been allowed to be rolled out to customers

**Comment by grafnull** [comment]
I had the same issue. Thanks to the community for the quick workaround.
Is this specific to a Linux release or version?

**Comment by GuillaumeHullin** [comment]
> I had the same issue. Thanks to the community for the quick workaround. Is this specific to a Linux release or version?

Don't think so. But Debian 12 here.

**Comment by ninji** [comment]
Same issue here after trying to solve new issues with HELO-Rejects from SMTP-Server.
Got different error messages from same call like "unknown option public on network", differs from call to call.
Ending up rebuilding from backup snapshot.

**Comment by yobyot** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Worked for me, too.

Sumthin's happening to quality in Bitwarden. After 18 months of quiet, reliable upgrades and new feature additions...suddenly this week, it's driving me crazy. I sure hope this is only a burp and not a slow descent.

**Comment by DanielGerecht** [comment]
After update nothing works with the error
ERROR: Version mismatch: file /srv/docker/bitwarden/bwdata/docker/docker-compose.yml specifies version 1 but extension file /srv/docker/bitwarden/bwdata/docker/docker-compose.override.yml uses version 3.0
and when i search for compose_ver in the /bwdata/config.yml nothing is there

**Comment by ninji** [comment]
Nope
`ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for services: 'api'
Unsupported config option for networks: 'public'
ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for services: 'attachments'
Unsupported config option for networks: 'default'
root@vault:/opt/bitwarden#
`

**Comment by mathias-ioki** [comment]
Same here. Looks like it's enough to add

```version: '3'```

at the start of the `bwdata/docker/docker-compose.yml` file as a workaroung.

**Comment by DanielGerecht** [comment]
> > Nope
> > ```
> > ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
> > Unsupported config option for services: 'api'
> > Unsupported config option for networks: 'public'
> > ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
> > Unsupported config option for services: 'attachments'
> > Unsupported config option for networks: 'default'
> > root@vault:/opt/bitwarden#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Rebuild with a new snapshot again...
> 
> I had the same issue with docker-compose version 1.25.1. I fixed it by updating to Docker Compose version v2.27.0 (https://docs.docker.com/compose/install/standalone/)

i did a VM Clone and this worked for me too, now im gonna do that on the Productive VM later today my docker-compose versionw as 1.26 despite the ubuntu package manage saying 1.29.0

**Comment by davidhildebrand** [comment]
Having the same problem here and the suggested workarounds haven't worked.

A couple days ago, an update failed with the error:
`Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization`

I've tried the manual `bitwarden.sh` patch, but it fails (note that it fails with all the stop/update/start commands with the same kind of error):
`bitwarden@zf:~$ ./bitwarden.sh update
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.4.1
Docker version 24.0.2, build cb74dfc
docker-compose version 1.26.2, build eefe0d31

ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for networks: 'public'
Unsupported config option for services: 'web'
bitwarden@zf:~$ `

Adding `version: '3'` to `bwdata/docker/docker-compose.yml` also did not work.

Any idea what else I can try to get around this issue?

**Comment by GuillaumeHullin** [comment]
Upgrade Docker?

This is my version data:
```
bitwarden.sh version 2024.4.2
Docker version 26.1.1, build 4cf5afa
Docker Compose version v2.27.0
```

**Comment by davidhildebrand** [comment]
Upgrading docker-compose did the trick (after resolving some docker login issues that resulted from the upgrade).  All set now, it seems.  Thanks!

**Comment by Nini81** [comment]
Same here, upgrading to latest docker-compose (2.27.0) and docker-ce (26.1.1) did the trick :
For Ubuntu / debian :
`# Check the current version of Docker Compose
docker-compose version

# Backup 
cp /usr/local/bin/docker-compose /usr/local/bin/docker-compose.bck

# Download the latest version of Docker Compose
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# Apply executable permissions to the binary
sudo chmod +x /usr/local/bin/docker-compose

# Verify the installation
docker-compose version`

**Comment by ninji** [comment]
**Success**

with following minor changes

- installing _docker-compose_ with the _curl_ method above or via link above (https://docs.docker.com/compose/install/standalone/) and set the x bit, remove other distribution docker-composes (1.25.0-1, 1.27.x, 1.29.x) or make sure bitwarden.sh find the 2.27 in path
- comment out the `compose_version` in `bwdata/config.yml` - it will be overwritten on next update

**Environment**

This work on the old 20.04 LTS Ubuntu on a VM.
This is essential because I have to maintain other self hosted instances without snapshot possibility for a rollback.
A update of docker.io (24.0.5) was not neccessary.

**Comment by Carded8521** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Hero! Worked for me too

**Comment by nkasco** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

+1 worked for me too

**Comment by DNRK** [comment]
> I tried commenting out `compose_version` in `bwdata/config.yaml` file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Thank you, worked for me

**Comment by Nurgus** [comment]
None of the solutions here were suitable for me - my docker-compose.yml needs the version: "3" line and I don't want to use the curl solution to update docker-compose.

My workaround is to run bitwarden.sh update, observe the error message, add version: "3" to docker-compose.override.yml. The version line should be the same in both docker-compose.override.yml and docker-compose.yml.
Then run bitwarden.sh start
