### ISSUE TITLE
2024.5.0 Update issue - Unhandled exception. YamlDotNet.Core.YamlException

### ISSUE THREAD

**Issue by JoshDi** [bitwarden/server#4100]
### Steps To Reproduce

When trying to update from 2024.4.1 to 2024.5.0, I get the following .NET error. Any ideas? 

```
./bitwarden.sh updateself
./bitwarden.sh update
```

### Expected Result

These two commands above should update my Bitwarden Instance, but it fails. 

### Actual Result

```
bitwarden@Xeon:~$ ./bitwarden.sh updateself
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.4.1
Docker version 26.1.3, build b72abbb
Docker Compose version v2.27.0

Updated self.
bitwarden@Xeon:~$ ./bitwarden.sh update
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.5.0
Docker version 26.1.3, build b72abbb
Docker Compose version v2.27.0

[+] Running 13/13
 ✔ Container bitwarden-sso            Removed                                                                 1.8s 
 ✔ Container bitwarden-notifications  Removed                                                                 1.6s 
 ✔ Container bitwarden-events         Removed                                                                 1.1s 
 ✔ Container bitwarden-nginx          Removed                                                                 2.0s 
 ✔ Container bitwarden-icons          Removed                                                                 1.7s 
 ✔ Container bitwarden-attachments    Removed                                                                 0.7s 
 ✔ Container bitwarden-web            Removed                                                                 0.5s 
 ✔ Container bitwarden-identity       Removed                                                                 0.9s 
 ✔ Container bitwarden-api            Removed                                                                 1.1s 
 ✔ Container bitwarden-admin          Removed                                                                 1.0s 
 ✔ Container bitwarden-mssql          Removed                                                                 0.5s 
 ✔ Network docker_default             Removed                                                                 0.3s 
 ✔ Network docker_public              Removed                                                                 0.6s 
2024.5.0: Pulling from bitwarden/setup
Digest: sha256:79bc6c1916d885194cc0fc501f0e92c46bdc78d7a84f72b73ea1e4febe9a730e
Status: Image is up to date for bitwarden/setup:2024.5.0
docker.io/bitwarden/setup:2024.5.0

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 315
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 163
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 57
```

### Additional Context

Looks to be the same as this issue [Bitwarden self host cannot start](https://community.bitwarden.com/t/bitwarden-self-host-cannot-start/66621)

### Build Version

2024.5.0

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04 LTS 64bit

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JoshDi** [comment]
fixed by commenting out `compose_version` in `bwdata/config.yaml` file
