### ISSUE TITLE
2024.5.0 update gives an YamlException in Bit.Setup.Configuration using the bitwarden.sh script

### ISSUE THREAD

**Issue by Ad-Blokker** [bitwarden/server#4101]
### Steps To Reproduce

The update was applied in this fashion:
1. Run ./bitwarden.sh updateself
2. Run ./bitwarden.sh update

### Expected Result

Retrieving, Building and starting all docker containers

### Actual Result

Parsing error on YAML file

```
./bitwarden.sh update
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.5.0
Docker version 26.1.3, build b72abbb
docker-compose version 1.29.2, build 5becea4c

Stopping bitwarden-nginx         ... done
Stopping bitwarden-admin         ... done
Stopping bitwarden-events        ... done
Stopping bitwarden-sso           ... done
Stopping bitwarden-api           ... done
Stopping bitwarden-web           ... done
Stopping bitwarden-mssql         ... done
Stopping bitwarden-icons         ... done
Stopping bitwarden-identity      ... done
Stopping bitwarden-notifications ... done
Stopping bitwarden-attachments   ... done
Removing bitwarden-nginx         ... done
Removing bitwarden-admin         ... done
Removing bitwarden-events        ... done
Removing bitwarden-sso           ... done
Removing bitwarden-api           ... done
Removing bitwarden-web           ... done
Removing bitwarden-mssql         ... done
Removing bitwarden-icons         ... done
Removing bitwarden-identity      ... done
Removing bitwarden-notifications ... done
Removing bitwarden-attachments   ... done
Removing network docker_default
Removing network docker_public
2024.5.0: Pulling from bitwarden/setup
09f376ebb190: Pull complete 
7248743022af: Pull complete 
95fcf2c5436c: Pull complete 
0fbaf16568f1: Pull complete 
e9e190cbc518: Pull complete 
a893f927642d: Pull complete 
26cf1b375588: Pull complete 
ec5ff5f79ce6: Pull complete 
e11f815dc34e: Pull complete 
aa8363be8d6d: Pull complete 
58596cf466c4: Pull complete 
Digest: sha256:79bc6c1916d885194cc0fc501f0e92c46bdc78d7a84f72b73ea1e4febe9a730e
Status: Downloaded newer image for bitwarden/setup:2024.5.0
docker.io/bitwarden/setup:2024.5.0

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 315
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 163
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 57
```

```
./bitwarden.sh rebuild
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.5.0
Docker version 26.1.3, build b72abbb
docker-compose version 1.29.2, build 5becea4c


Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 315
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 163
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 57
```

### Build Version

2024.5.0

### Environment

Self-Hosted

### Environment Details

- OS: Debian GNU/Linux 11 (bullseye)
- Env: Docker
- Hardware: VM (4 CPUs - 8GB RAM)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Ad-Blokker** [comment]
> I tried commenting out compose_version in bwdata/config.yaml file and it worked. Also after update finished this property is gone from config so this should be only one-time workaround.

Thanks to the comments in #4059
