### ISSUE TITLE
Organization view fail: Unknown column 'p.Gateway' in 'field list'

### ISSUE THREAD

**Issue by holow29** [bitwarden/server#4207]
### Steps To Reproduce

1. Go into admin console
2. Click 'Organizations' at the top
3. Click an organization

### Expected Result

I would expect the organization details to load

### Actual Result

Nginx 404 page and when going back, an error stating `Unknown column 'p.Gateway' in 'field list'`

### Additional Context

Admin.log:
```c
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      => SpanId:4eaed1c933ea2306, TraceId:4ca1c439da42208a053d05bd15d84082, ParentId:xxxxxxxxxxxxxxxx => ConnectionId:0HN4H6D74D29G => RequestPath:/admin/organizations/view/7823390c-o65d-4f1e-a1d6-af8e015a278a RequestId:0HN4H6D74D29G:00000001 => Bit.Admin.AdminConsole.Controllers.OrganizationsController.View (Admin)
      Failed executing DbCommand (108ms) [Parameters=[@__organizationId_0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT `p`.`Id`, `p`.`BillingEmail`, `p`.`BillingPhone`, `p`.`BusinessAddress1`, `p`.`BusinessAddress2`, `p`.`BusinessAddress3`, `p`.`BusinessCountry`, `p`.`BusinessName`, `p`.`BusinessTaxNumber`, `p`.`CreationDate`, `p`.`Enabled`, `p`.`Gateway`, `p`.`GatewayCustomerId`, `p`.`GatewaySubscriptionId`, `p`.`Name`, `p`.`RevisionDate`, `p`.`Status`, `p`.`Type`, `p`.`UseEvents`
      FROM `Provider` AS `p`
      INNER JOIN `ProviderOrganization` AS `p0` ON `p`.`Id` = `p0`.`ProviderId`
      WHERE `p0`.`OrganizationId` = @__organizationId_0
      LIMIT 1
fail: Microsoft.EntityFrameworkCore.Query[10100]
      => SpanId:4eaed1c933ea2306, TraceId:4ca1c439da42208a053d05bd15d84082, ParentId:xxxxxxxxxxxxxxxx => ConnectionId:0HN4H6D74D29G => RequestPath:/admin/organizations/view/7823390c-o65d-4f1e-a1d6-af8e015a278a RequestId:0HN4H6D74D29G:00000001 => Bit.Admin.AdminConsole.Controllers.OrganizationsController.View (Admin)
      An exception occurred while iterating over the results of a query for context type 'Bit.Infrastructure.EntityFramework.Repositories.DatabaseContext'.
      MySqlConnector.MySqlException (0x80004005): Unknown column 'p.Gateway' in 'field list'
         at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 962
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
         at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
         at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 337
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      MySqlConnector.MySqlException (0x80004005): Unknown column 'p.Gateway' in 'field list'
         at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 962
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
         at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
         at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 337
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

Api.log:
```c
fail: Bit.Core.Billing.Queries.Implementations.SubscriberQueries[0]
      => SpanId:17125e3facb67119, TraceId:00df5f9a718d017c6192bd33191f5cd5, ParentId:xxxxxxxxxxxxxxxx => ConnectionId:0HN3K7IG135PL => RequestPath:/organizations/7823390c-o65d-4f1e-a1d6-af8e015a278a/billing/metadata RequestId:0HN3K7IG135PL:00000001 => Bit.Api.Billing.Controllers.OrganizationBillingController.GetMetadataAsync (Api)
      Cannot retrieve subscription for subscriber (7823390c-o65d-4f1e-a1d6-af8e015a278a) with no GatewaySubscriptionId
```

_Certain IDs edited for privacy_

### Githash Version

8e1ad16f-dirty

### Environment Details

Docker bitwarden-unified self-host:beta [2024.6.1-beta](https://hub.docker.com/layers/bitwarden/self-host/2024.6.1-beta/images/sha256-9b9927ce7e39dcb03196120d54f790857a239842ca8c105ecb5d3fd436150bd7?context=explore)
Server: 2024.6.1
Web: 2024.6.0

### Database Image

MariaDB 11.4.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by holow29** [comment]
Appears to be resolved now. I am not sure when it was fixed, but working on [2024.7.2-beta](https://hub.docker.com/layers/bitwarden/self-host/2024.7.2-beta/images/sha256-746f057421a8fec924662325395d7de53d524799ee56c9dd3078336ff8e91c20?context=explore)
