### ISSUE TITLE
Error running sso and identity containers

### ISSUE THREAD

**Issue by beeritis** [bitwarden/server#4530]
### Steps To Reproduce

I've installed bitwarden as per https://bitwarden.com/help/install-on-premise-manual/ . 

I am running on RHEL9.4 , using podman-compose 1.0.6, podman version is 4.9.4

We use the standard `podman-compose  -d` command to start the containers. After a battle with SELinux ,most of which come up fine  with no further errors apart from sso and identity. 

For these two we get the same error : 

```
Unhandled exception. System.Exception: No identity certificate to use.
   at Bit.SharedWeb.Utilities.ServiceCollectionExtensions.AddIdentityServerCertificate(IIdentityServerBuilder identityServerBuilder, IWebHostEnvironment env, GlobalSettings globalSettings) in /home/runner/work/server/server/src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:line 519
   at Bit.Identity.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IWebHostEnvironment env, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Identity/Utilities/ServiceCollectionExtensions.cs:line 25
   at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/runner/work/server/server/src/Identity/Startup.cs:line 135
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bit.Identity.Program.Main(String[] args) in /home/runner/work/server/server/src/Identity/Program.cs:line 10
Unhandled exception. System.Exception: No identity certificate to use.
```

The containers run long enough to confirm that the certificates, private key and PFX are present in `/etc/bitwarden/identity` (within the container) so I know the volumes are being mounted correctly (also tested with working containers to confirm) . 

There are no permission errors so I don't think that is the issue, I've even tried running with normal docker vs podman but the same issue is present. 

I thought it could be the env file but the `uid.env` is passed through correctly. 

I cannot work out what else it might be. Any help would be very much appreciated. 

Thanks

### Expected Result

Containers to run sucessfully without error

### Actual Result

For these two containers (sso / identity) we get the same error : 

```
Unhandled exception. System.Exception: No identity certificate to use.
   at Bit.SharedWeb.Utilities.ServiceCollectionExtensions.AddIdentityServerCertificate(IIdentityServerBuilder identityServerBuilder, IWebHostEnvironment env, GlobalSettings globalSettings) in /home/runner/work/server/server/src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:line 519
   at Bit.Identity.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IWebHostEnvironment env, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Identity/Utilities/ServiceCollectionExtensions.cs:line 25
   at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/runner/work/server/server/src/Identity/Startup.cs:line 135
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bit.Identity.Program.Main(String[] args) in /home/runner/work/server/server/src/Identity/Program.cs:line 10
Unhandled exception. System.Exception: No identity certificate to use.
```

The containers run long enough to confirm that the certificates, private key and PFX are present in `/etc/bitwarden/identity` (within the container) so I know the volumes are being mounted correctly (also tested with working containers to confirm) . 

There are no permission errors so I don't think that is the issue, I've even tried running with normal docker vs podman but the same issue is present. 

I thought it could be the env file but the `uid.env` is passed through correctly. 

I cannot work out what else it might be. Any help would be very much appreciated. 

Thanks

### Build Version

latest tag 

### Environment

Self-Hosted

### Environment Details

RHEL9.4 , podman compose 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Podman is currently not supported.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by beeritis** [comment]
@Neonwarden 

Finally found the solution to this. 

This had nothing to do with podman being an issue. 

This was down to bad documentation  e.g.  https://bitwarden.com/help/install-on-premise-manual/ . 

Unless I completely missed it, there is nowhere in the guide that it tells you to add this setting to the `global.env` / `global.override.env` . The setting is `globalSettings__selfHosted=true` , without this, the sso and identity containers will never find the PFX certificate 

I had only found out by following the code and spotted the setting here https://github.com/bitwarden/server/blob/main/src/Core/Settings/GlobalSettings.cs#L20 . 


Please can the documentation be updated to reflect this as I spent a couple of days trying to work this out and I am sure it will help others!

Thanks,
