### ISSUE TITLE
Javascript Error when updating

### ISSUE THREAD

**Issue by Undianer** [bitwarden/server#459]
I'm having an issue, when I try to update to version 1.14.0.

```
A javascript error occured in the main process

Uncaught Exception:
Error: spawn
[path]\AppData\Roaming\Bitwarden\_update_\Bitwarden-Installer-1.14.0.exe
EACCES
at Process.ChildProcess._handle.onexit(internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
```
![Annotation 2019-03-17 105207](https://user-images.githubusercontent.com/10446556/54488510-bd56e080-48a2-11e9-9342-fd355b156e5a.jpg)

BR
Andreas

**Comment by kspearrin** [comment]
https://github.com/bitwarden/desktop/issues/228
