### ISSUE TITLE
mobile app stops working on all devices

### ISSUE THREAD

**Issue by walkerprog** [bitwarden/server#514]
a while ago all our apps on mobile phone stopped syncing. as the app still was logged in it was not detected immediately by us so I cannot tell what exactly happend or when exactly the apps stopped working. All mobile phones are affected: Android, IOS. It doesn't matter if local network or from outside.
The vault can not be opened on these devices too. Loading the page in Chrome or Firefox or trying to login in the app takes AGES till timeout.
Today I updated to bitwarden server 1.30.4. The problem still exists.

Even the replacement of the company firewall didn't help.
The firewall on the linux machine ist deactivated and flushed except the needed rules to allow bitwarden to send mails (or other traffic) out.

The only helpful message I get on the server from docker logs -ft bitwarden-identity is:

2019-06-10T20:37:10.529481206Z info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2019-06-10T20:37:10.529527906Z       Request starting HTTP/1.0 POST http://ourURL/connect/token application/x-www-form-urlencoded 274
2019-06-10T20:37:10.529889206Z info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
2019-06-10T20:37:10.529914006Z       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
2019-06-10T20:37:10.661650506Z warn: Microsoft.AspNetCore.Identity.UserManager[0]
2019-06-10T20:37:10.661697006Z       Invalid password for user some_cryptic_userid.
2019-06-10T20:37:12.688005006Z info: IdentityServer4.Validation.TokenRequestValidator[0]
2019-06-10T20:37:12.688050706Z       User authentication failed: invalid_username_or_password, request details: {
2019-06-10T20:37:12.688058906Z         "ClientId": "mobile",
2019-06-10T20:37:12.688072006Z         "GrantType": "password",
2019-06-10T20:37:12.688078506Z         "Scopes": "api offline_access",
2019-06-10T20:37:12.688092006Z         "UserName": "some username",
2019-06-10T20:37:12.688098506Z         "Raw": {
2019-06-10T20:37:12.688104006Z           "grant_type": "password",
2019-06-10T20:37:12.688109706Z           "username": "some username",
2019-06-10T20:37:12.688115306Z           "password": "***REDACTED***",
2019-06-10T20:37:12.688120706Z           "scope": "api offline_access",
2019-06-10T20:37:12.688126206Z           "client_id": "mobile",
2019-06-10T20:37:12.688131706Z           "DeviceType": "Android",
2019-06-10T20:37:12.688137106Z           "DeviceIdentifier": "some cryptic Identifier",
2019-06-10T20:37:12.688142606Z           "DeviceName": "some device name",
2019-06-10T20:37:12.688190106Z           "DevicePushToken": ""
2019-06-10T20:37:12.688198706Z         }
2019-06-10T20:37:12.688204106Z       }
2019-06-10T20:37:12.695283406Z info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-06-10T20:37:12.695330806Z       Request finished in 2165.8837ms 400 application/json; charset=UTF-8

everything else works fine. Win10-App, Web-Vault
certificate is not self signed and used by MANY of our services, no mobile phone has problems with this so I doubt that there could be a problem.

I'm not an expert on docker, am glad to have it running, so I'm out of ideas for further debugging, sorry about that.
If you need further information please let me know how to get them and I will try my best.

Best regards

ps: please excuse my horrible english ^^

**Comment by kspearrin** [comment]
1.30.4 is the latest, so I am not sure why your containers are not the latest. Try running this (again?):

```
./bitwarden.sh updateself
./bitwarden.sh update
```

**Comment by walkerprog** [comment]
after running the upgrade again docker ps now outputs:

CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS              PORTS                                                     NAMES
e42f7bb228e6        bitwarden/nginx:1.30.4           "/entrypoint.sh"    54 seconds ago      Up 51 seconds       80/tcp, IP:80->8080/tcp, IP:443->8443/tcp   bitwarden-nginx
6859a67885d7        bitwarden/admin:1.30.4           "/entrypoint.sh"    56 seconds ago      Up 53 seconds       5000/tcp                                                  bitwarden-admin
f8401b2f5def        bitwarden/identity:1.30.4        "/entrypoint.sh"    58 seconds ago      Up 55 seconds       5000/tcp                                                  bitwarden-identity
1bd9507b941f        bitwarden/icons:1.30.4           "/entrypoint.sh"    58 seconds ago      Up 55 seconds       5000/tcp                                                  bitwarden-icons
dd1169449cb1        bitwarden/attachments:1.30.4     "/entrypoint.sh"    58 seconds ago      Up 55 seconds       5000/tcp                                                  bitwarden-attachments
ff9933f5262b        bitwarden/mssql:1.30.4           "/entrypoint.sh"    58 seconds ago      Up 55 seconds       1433/tcp                                                  bitwarden-mssql
d05ee1ebcda5        bitwarden/api:1.30.4             "/entrypoint.sh"    58 seconds ago      Up 55 seconds       5000/tcp                                                  bitwarden-api
0b18bf2b2aec        bitwarden/web:2.10.1             "/entrypoint.sh"    58 seconds ago      Up 55 seconds       5000/tcp                                                  bitwarden-web
b0f47e57670e        bitwarden/notifications:1.30.4   "/entrypoint.sh"    58 seconds ago      Up 56 seconds       5000/tcp                                                  bitwarden-notifications


bitwardenurl/admin now shows the right version, too.


problem with mobile phones not able to login still persistent

**Comment by kspearrin** [comment]
I am not sure why logins would not work from a mobile client only. Can you log into the web vault from those same mobile devices?

**Comment by walkerprog** [comment]
yes, I can (for the moment)
right now I am logged in in chrom into the web vault
mobile app still not able to login, now outputs "There is a problem connecting to the server."
does the app any own DNS caching or something like this? The bitwarden-record has a ttl of 60 seconds internal and external so it should switch rather quickly.
As the web vault is perfectly functional in internal network I do not see any reason the mobile app on the same device is not able to connect to the same server ten seconds later while the web vault is functional all the time

**Comment by kspearrin** [comment]
Did you change anything with the server's certificates? The mobile apps have more strict requirements for valid SSL certs than the browser apps. If there are any SSL issues they would fail to connect to the server.

**Comment by walkerprog** [comment]
the certificate should not be the problem
it is perfectly valid, all device and apps have no problem with it
the certificate is used since the installation of bitwarden months ago and was not touched since then
I would belief in some changes Android or Apple did to the processing of certificates in their OS, but not both at the same time.
Sadly I don't have a windows phone yet to check the behaviour on it with our server

**Comment by kspearrin** [comment]
What do the server logs (API and Identity) show when you get the error? What you showed before on Identity is an incorrect email/password error, which does not correspond to the "There is a problem connecting to the server." error you mentioned later.

**Comment by walkerprog** [comment]
Sorry for the delayed answer, I have tested a lot the last weeks.

The problem that it really took ages to connect to the bitwarden server from outside is nailed down to the Web Application Proxies (WAP role Windows). I still don't really understand this, because all other websites and services are perfectly functional over the reverse proxies but at least it means that this is not a general problem inside our bitwarden server.

All clients inside and outside the network can connect perfectly with the bitwarden server.
This includes all Windows Workstations and servers with Windows app installed, ALL! devices per browser and all iOS devices per iOS app.

On Android the web vault of our server works perfectly (Chrome, Firefox, Opera), but this is the device a connection via Android app is still not possible. Neither inside nor outside the network.
The error message inside the app ist still just a generic "Es ist ein Fehler aufgetreten. There is a problem connecting to the server." (Did I mention the use of the german version?)

On server side the connection is done on - the app is not trying to connect to another server or something else:
13:46:19.639418 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [S], seq 1079772217, win 65535, options [mss 1460,sackOK,TS val 14222455 ecr 0,nop,wscale 8], length 0
13:46:19.639469 IP bitwardenserverIP.443 > AndroidIP.38889: Flags [S.], seq 2017496241, ack 1079772218, win 28960, options [mss 1460,sackOK,TS val 993475757 ecr 14222455,nop,wscale 7], length 0
13:46:19.641638 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [.], ack 1, win 343, options [nop,nop,TS val 14222456 ecr 993475757], length 0
13:46:19.643294 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [P.], seq 1:201, ack 1, win 343, options [nop,nop,TS val 14222456 ecr 993475757], length 200
13:46:19.643323 IP bitwardenserverIP.443 > AndroidIP.38889: Flags [.], ack 201, win 235, options [nop,nop,TS val 993475761 ecr 14222456], length 0
13:46:19.657522 IP bitwardenserverIP.443 > AndroidIP.38889: Flags [P.], seq 1:2465, ack 201, win 235, options [nop,nop,TS val 993475775 ecr 14222456], length 2464
13:46:19.659396 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [.], ack 1449, win 354, options [nop,nop,TS val 14222457 ecr 993475775], length 0
13:46:19.659581 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [.], ack 2465, win 365, options [nop,nop,TS val 14222457 ecr 993475775], length 0
13:46:19.674977 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [P.], seq 201:208, ack 2465, win 365, options [nop,nop,TS val 14222459 ecr 993475775], length 7
13:46:19.675377 IP bitwardenserverIP.443 > AndroidIP.38889: Flags [F.], seq 2465, ack 208, win 235, options [nop,nop,TS val 993475793 ecr 14222459], length 0
13:46:19.675752 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [R.], seq 208, ack 2465, win 365, options [nop,nop,TS val 14222459 ecr 993475775], length 0
13:46:19.679264 IP AndroidIP.38889 > bitwardenserverIP.443: Flags [R], seq 1079772425, win 0, length 0


bitwarden-identity keeps completely quiet

bitwarden-nginx:
2019-06-11T15:44:30.503830738Z nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/DOMAIN/certificate.crt"
2019-06-17T23:49:09.950126406Z nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/DOMAIN/certificate.crt"
2019-07-14T23:43:40.909457800Z nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/DOMAIN/certificate.crt"
nothing interesting so far for me

bitwarden-api keeps silent, last logs are from a windows app client:
2019-07-26T11:43:08.869520162Z info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
2019-07-26T11:43:08.869536362Z       Executed action Bit.Api.Controllers.AccountsController.GetAccountRevisionDate (Api) in 77.0675ms
2019-07-26T11:43:08.869544762Z info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-07-26T11:43:08.869552562Z       Request finished in 78.2007ms 200 application/json; charset=utf-8

bitwarden-web keeps as clean as the other logfiles

iptables are empty except a rule to allow outgoing traffic (espacially for mailing from bitwarden admin to login):
MASQUERADE  all  --  172-0-0-0.lightspeed.brhmal.sbcglobal.net/8  anywhere

I am officially out of ideas now, why everything works expect this Android app (was reinstalled several times)


VERSION
Server Installed    1.30.4
Server Latest   1.30.4
Web Installed   2.10.1
Web Latest  2.10.1

Android app version (a lot updates last weeks, no update helped):
Google Play states 2.1.0

**Comment by kspearrin** [comment]
Usually, when there are problems connecting to the server that are exclusive to the Android app, it is a certificate issue. The Android app has stricter requirements for certificate validation. What type of certificate is being used here?

**Comment by walkerprog** [comment]
It doubt it is a certificate issue
certificate is a wildcard certificate issued by Thawte, chain: DigiCert Global Root G2-> Thawte TLS RSA CA G1 -> our cert
same certificate works in all other apps on this android, inclusing exchange, Webservices
if the certificate was not valid or something else android would also block it in chrome browser?
But chrome browser on this android is working perfectly

**Comment by kspearrin** [comment]
In past issues, we have found certificate validation to work in the Android browser but fail in the app, much like you are describing here.

Is this Bitwarden instance publicly available? Would I be able to attempt a connection to try and debug it?

**Comment by walkerprog** [comment]
Oh, ok, that is new to me
Thougt validation in app and in browser is the same on android

Yes, it is publicy reachable
Where to send you the URL in private?

**Comment by kspearrin** [comment]
Please send an email referencing this issue to support@bitwarden.com

**Comment by walkerprog** [comment]
mail is out, I hope you can see something during debugging

**Comment by kspearrin** [comment]
As I suspected, it appears your server has a cert issue. Check this page for more info: https://www.digicert.com/help/


> The server is not sending the required intermediate certificate.

**Comment by walkerprog** [comment]
oh, shame on me
I have corrected the ca-chain
digicert now states that everything is correct

error in android app still the same

**Comment by kspearrin** [comment]
Here is the error from the Android app:

```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.


  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
  at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect () [0x0000a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 () [0x0005a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x0012e] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002be] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
  at Bit.Core.Services.ApiService.SendAsync[TRequest,TResponse] (System.Net.Http.HttpMethod method, System.String path, TRequest body, System.Boolean authed, System.Boolean hasResponse) [0x0029d] in C:\Projects\bitwarden\mobile\src\Core\Services\ApiService.cs:394 
  --- End of managed Javax.Net.Ssl.SSLHandshakeException stack trace ---
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
	... 12 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 23 more
```

**Comment by walkerprog** [comment]
Hallo Kyle,

thank you very much for that hint, I have nailed it down now.

At first I have put the wrong intermediate an ca into the certificate (sha1 instead sha2).
Shame on me I didn't get it before

But second: it works only WITHOUT the root ca in the certificate for me, so:
private.key of course has to contain the key
certificate.crt hast to contain the cert and the intermediate only
ca.crt has to contain the root ca

As everything is working now this issue can be closed.
Thank you very much for your time and help.

The only problem left (but another issue) is the speed and reliability over Windows WAP. Do you have any experience with bitwarden hostet behind Windows WAP?

**Comment by kspearrin** [comment]
I have no experience with Windows WAP, sorry.

**Comment by styleart** [comment]
I get the same error with the cloud version (no self-hosting) with latest release on Android 9. Can't login anymore.
