### ISSUE TITLE
Error sending validation email, probably identity issue

### ISSUE THREAD

**Issue by Aguay-val** [bitwarden/server#532]
Hi there,
I'm trying to finish my bitwarden install on my serveur but i still have an issue.

## Platform 
OS : Debian 10 
RAM : 4G
Docker from repo.
Self signed certificate from bitwarden script.

## Issue

I'm able to use the bitwarden.sh to create my bitwarden server. After i change `env/global.override.env` to use my email server i'm launching my server.

I'm able to create an account and get a "Welcome" email.
But after i logged in i'm clicking on "verify my email" and i can't have my verification email.

When i'm looking into the log, here what i have : 

```bitwarden-notifications | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-notifications |       Request starting HTTP/1.0 POST http://notifications:5000/hub/negotiate text/plain;charset=UTF-8 0                                                                                                          
bitwarden-notifications | fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
bitwarden-notifications |       Exception occurred while processing message.
bitwarden-notifications | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://identity:5000/.well-known/openid-configuration'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from:
'http://identity:5000/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).                                                             
bitwarden-notifications |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)                                                                                         
bitwarden-notifications |    --- End of inner exception stack trace ---
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)                                                                                         
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)                                       
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)                                                                                                   
bitwarden-notifications |    --- End of inner exception stack trace ---
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)                                                                                                   
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()                                                                                                                   
bitwarden-notifications | fail: Microsoft.AspNetCore.Server.Kestrel[13]
bitwarden-notifications |       Connection id "0HLOBESPB26V6", Request id "0HLOBESPB26V6:00000001": An unhandled exception was thrown by the application.
bitwarden-notifications | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://identity:5000/.well-known/openid-configuration'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from:
'http://identity:5000/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
bitwarden-notifications |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
bitwarden-notifications |    --- End of inner exception stack trace ---
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
bitwarden-notifications |    --- End of inner exception stack trace ---
bitwarden-notifications |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
bitwarden-notifications |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
bitwarden-notifications |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
bitwarden-notifications |    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
bitwarden-notifications |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

It looks like there is a problem with the identity server. But i'm using your system without any tweak.

## Admin sections of bitwarden

However, when i use the "admin sections" the "magic link" is working well. So it's not an email issue, it's really related to "identity" web service.

I don't know where to looking for to solved the problem.

Any help would be great.

**Comment by Aguay-val** [comment]
Hi again. 
After few hours i finally get into the containers with `docker exec -it <id> bash ` and do "simple" stuff like doing a curl.

I realized that the containers was trying to go to the proxy instead of using the webservice.

Consider it resolved.

Thanks :)
