### ISSUE TITLE
Can't configure localhost as smtp host on self hosted instance

### ISSUE THREAD

**Issue by WebFreak001** [bitwarden/server#545]
I'm trying to setup mail support in my bitwarden instance with my local postfix mail server running on localhost, but when I configure it in `bwdata/env/global.override.env` to

```
globalSettings__mail__replyToEmail=bwadmin@example.org
globalSettings__mail__smtp__host=127.0.0.1
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=user
globalSettings__mail__smtp__password=pass
```

it doesn't seem to work and trying to send confirmation mails shows an "An unhandled server error has occurred" error on the web UI.

<details>

<summary>Error log</summary>

```
2019-08-15 14:13:27.264 +00:00 [Error] Connection refused 127.0.0.1:587
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 127.0.0.1:587
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 83
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /home/appveyor/projects/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 47
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 450
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /home/appveyor/projects/server/src/Api/Controllers/AccountsController.cs:line 147
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

</details>

Manually writing an SMTP message using `nc 127.0.0.1 587` works fine, it just seems that bitwarden has problems connecting to the server (self hosted)

Also just ran the update script. I would assume this is some docker container configuration issue which I can't change using that global config file?

**Comment by kspearrin** [comment]
Seems like a networking issue. Is `127.0.0.1 587` reachable from inside the docker containers themselves?

**Comment by WebFreak001** [comment]
neither in bitwarden-nginx, in bitwarden-web, nor in bitwarden-api the host is reachable. Outside the containers it is reachable, so I think it's just missing some configuration here to make it reachable

**Comment by kspearrin** [comment]
Yes, you likely need to make some networking configuration to the docker-compose file so that you can access your host network from inside the containers.

**Comment by WebFreak001** [comment]
hm I was hoping for some solution in the config because it says the file is generated and will be overwritten on update and managing that override file seems like it will quickly cause issues when it can't merge the files. Also because it would be cool if it would automatically detect 127.0.0.1 as host and based on that automatically forward the specified port.

In what container does the port need to be specified / what container does the mailing? I checked the help center but there doesn't seem to be a lot of technical details about this.

**Comment by WebFreak001** [comment]
I tried making the api container connect to the host network instead of the docker default one, but it seems nginx has problems finding it then and it also shows permanently as "starting"

When I tried exposing port 587 to the container, localhost still wouldn't work so I tried searching for how to access it. I installed iproute2 in the api container and checked what IP it might use and found "172.25.0.9" which looks not very generic and not like how I should hard code it. Still wanted to try it and it still failed connecting. For all the tests I adjusted the postfix config to allow 172.25.0.0/16 and 172.17.0.0/16 because they show up as docker networks in my host machine. I tried 172.17.0.1 too because it showed up on the host system but that also didn't work.

```
root@2c9feb566f62:/app# ip route show
default via 172.25.0.1 dev eth0 
172.25.0.0/16 dev eth0 proto kernel scope link src 172.25.0.9 
root@2c9feb566f62:/app# curl http://172.25.0.1:587
curl: (7) Failed to connect to 172.25.0.1 port 587: Connection refused
root@2c9feb566f62:/app# curl http://172.25.0.9:587
curl: (7) Failed to connect to 172.25.0.9 port 587: Connection refused
```

(I'm using curl here because it will also show if the service is properly working because it will just dump what the service responds and because it's already installed in the container)

So I don't think trying to get it to work in that network is a good idea. The ip keeps changing and even when I setup a simple `nc -l` server on the host machine listening on some IP of the container it keeps saying connection refused.

So far I have been using bitwarden for over a year without this but it would still be nice having the password recovery emails working just in case.

Is there maybe some way to install bitwarden not over docker? It seems like a hassle trying to do modifications to it and it doesn't play very well with the host system or my network configuration and systemd services.

Otherwise is there a way to make the containers work in the host network instead of some local docker network?

**Comment by edermi** [comment]
Does your server have a static IP / domain name? Allowing connections to mail on the local interface of the server and addressing it via its public IP / domain name from within Bitwarden should work.

I think trying to change network settings and bridging it to the host network is a rather bad idea since you probably enable direct access to all bitwarden containers to anybody on your host / network.

**Comment by WebFreak001** [comment]
Trying to access any port with any listener via public IP currently does not work, probably because of my firewall settings. It only starts working once I listen on 0.0.0.0, however I don't want to risk having my mail server submission port open. The firewall seems to work for this, but I think it might cause issues with other services in postfix which listens to the IPs I specify and I want to be safe with my mail server (in case the firewall doesn't start up properly or is misconfigured).

I'm currently most confused why it doesn't work simply accessing the host IP of the docker interface and listening on exactly that address range too, but I don't have enough docker experience to really debug that and make it work. With all the things I described in my previous comment I don't really know anything else I can try to make direct access work.

**Comment by edermi** [comment]
Did you try:

- Binding postfix to 0.0.0.0
- restrict access via firewall to lo/docker interfaces

This should be fine in the first place, if this works you can try to narrow down which communication associations are actually needed

**Comment by c4539** [comment]
Hey,
127.0.0.1 inside the container loops back to the container itself.
In order to make a connection from the container to your host, you need to use the hosts real IP address.
