### ISSUE TITLE
Local Domains

### ISSUE THREAD

**Issue by pclever1** [bitwarden/server#594]
I am trying to install bitwarden for my first time and I am trying to use a domain with the suffix ".local". This is a valid suffix for windows active directory and when I try to use it in the bitwarden install I get this error:
`The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "mydomain.local": Domain name does not end with a valid public suffix (TLD)`

I would assume this project would be able to function with it. Can someone tell me if there is a way around this error that doesn't involve changing my networks domain? Thank you!

**Comment by pclever1** [comment]
My apologizes, I forgot to add this VM to the domain. That fixed this issue but another one persisted unfortunately. I feel like this might be another miss-configuration on my part but I don't see a good way to debug this. Again please let me know if you have any ideas on what my issue is.

> An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159,                                                                                                                                                              in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line                                                                                                                                                              57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):

  

> File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              600, in urlopen chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 301,                                                                                                                                                              in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168,                                                                                                                                                              in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnecti                                                                                                                                                             on object at 0x7f8623d6fcd0>: Failed to establish a new connection: [Errno -3] T                                                                                                                                                             ry again

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):

>   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449,                                                                                                                                                              in send timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                                                                                                              638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399,                                                                                                                                                              in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsenc                                                                                                                                                             rypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewCo                                                                                                                                                             nnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8623d6f                                                                                                                                                             cd0>: Failed to establish a new connection: [Errno -3] Try again'))

> During handling of the above exception, another exception occurred:

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.lets                                                                                                                                                             encrypt.org', port=443): Max retries exceeded with url: /directory (Caused by Ne                                                                                                                                                             wConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8623                                                                                                                                                             d6fcd0>: Failed to establish a new connection: [Errno -3] Try again'))

> Please see the logfiles in /etc/letsencrypt/logs for more details.

**Comment by kspearrin** [comment]
At what point does this error occur? Need more context, please.

**Comment by pclever1** [comment]
Thanks for responding, I continued messing around with it and I am still getting a TLD error when generating an SSL.
After joining the VM to the domain and installing docker I ran the "./bitwarden.sh install" command and entered my information. It errors out when trying to obtain a new certificate. If I choose not to use "Let's Encrypt" to generate a SSL, everything works fine.
