### ISSUE TITLE
After restore: Cant login to my account. Bitwarden-Identity says: PKCS12_parse:mac verify failure

### ISSUE THREAD

**Issue by UnkwnUsr** [bitwarden/server#616]
Hello,
after i restored the following data in a new bitwarden server instance:

- bwdata/mssql/data
- bwdata/env

i get the following error from the container bitwarden-identity, which is always restarting:

```
bitwarden-identity | Unhandled Exception: Interop+Crypto+OpenSslCryptographicException: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
bitwarden-identity |    at Internal.Cryptography.Pal.OpenSslPkcs12Reader.Decrypt(SafePasswordHandle password)
bitwarden-identity |    at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts)
bitwarden-identity |    at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(SafeBioHandle bio, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
bitwarden-identity |    at Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, SafePasswordHandle password)
bitwarden-identity |    at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
bitwarden-identity |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
bitwarden-identity |    at Bit.Core.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IHostingEnvironment env, GlobalSettings globalSettings) in /home/appveyor/projects/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 336
bitwarden-identity |    at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/server/src/Identity/Startup.cs:line 61
bitwarden-identity | --- End of stack trace from previous location where exception was thrown ---
bitwarden-identity |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
bitwarden-identity |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
bitwarden-identity |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
bitwarden-identity |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
bitwarden-identity |    at Bit.Identity.Program.Main(String[] args) in /home/appveyor/projects/server/src/Identity/Program.cs:line 13
bitwarden-identity exited with code 139
```

Also if i want to login myself into the application it throws the following error:
Unhandled exepion

Is there a resoltion for this?

**Comment by Mart124** [comment]
Can't you restore the whole `bwdata` folder ?

**Comment by UnkwnUsr** [comment]
Problem solved. After i copied the complete env folder, the generated identity password for this installation got overwritten. So bitwarden couldnt use the old key with the new generated identity file.

I installed bitwarden again and only changesd the necessary keys (example: mssql sa password, connection string) and now it works :-)
