### ISSUE TITLE
Problem with email verification on-permis installation 

### ISSUE THREAD

**Issue by Youness1500** [bitwarden/server#629]
Hi All,

I have a problem with Bitwarden for sending emails does not work
![4](https://user-images.githubusercontent.com/53577391/71589388-f7892a00-2b24-11ea-9374-090cf2bb7f49.PNG)

my configuration is like this:

I ping my smtp server

also my configuration for SMTP works:

Best Regards

Youness

**Comment by kspearrin** [comment]
Can you check the server logs under `./bwdata/logs/Api` and see what the actual server error is?

**Comment by Youness1500** [comment]
Hi kspearrin,
Thank you for your support.

the logs in ./bwdata/logs/api/Api/20191231.txt is like this: 

2019-12-31 00:00:00.017 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 00:00:00.
2019-12-31 00:00:00.026 +00:00 [Information] It's alive!
2019-12-31 00:00:00.028 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 00:00:00.
2019-12-31 00:00:00.059 +00:00 [Information] Starting job "ValidateUsersJob" at 12/31/2019 00:00:00.
2019-12-31 00:00:00.401 +00:00 [Information] Validating premium for 0 users.
2019-12-31 00:00:00.401 +00:00 [Information] Finished job "ValidateUsersJob" at 12/31/2019 00:00:00.
2019-12-31 00:30:00.008 +00:00 [Information] Starting job "ValidateOrganizationsJob" at 12/31/2019 00:30:00.
2019-12-31 00:30:00.325 +00:00 [Information] Validating licenses for 0 organizations.
2019-12-31 00:30:00.329 +00:00 [Information] Finished job "ValidateOrganizationsJob" at 12/31/2019 00:30:00.
2019-12-31 01:00:00.010 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 01:00:00.
2019-12-31 01:00:00.013 +00:00 [Information] It's alive!
2019-12-31 01:00:00.013 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 01:00:00.
2019-12-31 02:00:00.013 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 02:00:00.
2019-12-31 02:00:00.025 +00:00 [Information] It's alive!
2019-12-31 02:00:00.043 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 02:00:00.
2019-12-31 03:00:00.009 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 03:00:00.
2019-12-31 03:00:00.010 +00:00 [Information] It's alive!
2019-12-31 03:00:00.012 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 03:00:00.
2019-12-31 04:00:00.013 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 04:00:00.
2019-12-31 04:00:00.013 +00:00 [Information] It's alive!
2019-12-31 04:00:00.013 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 04:00:00.
2019-12-31 05:00:00.007 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 05:00:00.
2019-12-31 05:00:00.009 +00:00 [Information] It's alive!
2019-12-31 05:00:00.010 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 05:00:00.
2019-12-31 06:00:00.011 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 06:00:00.
2019-12-31 06:00:00.011 +00:00 [Information] It's alive!
2019-12-31 06:00:00.011 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 06:00:00.
2019-12-31 06:00:00.012 +00:00 [Information] Starting job "ValidateUsersJob" at 12/31/2019 06:00:00.
2019-12-31 06:00:00.292 +00:00 [Information] Validating premium for 0 users.
2019-12-31 06:00:00.292 +00:00 [Information] Finished job "ValidateUsersJob" at 12/31/2019 06:00:00.
2019-12-31 07:00:00.006 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 07:00:00.
2019-12-31 07:00:00.007 +00:00 [Information] It's alive!
2019-12-31 07:00:00.010 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 07:00:00.
2019-12-31 08:00:00.010 +00:00 [Information] Starting job "AliveJob" at 12/31/2019 08:00:00.
2019-12-31 08:00:00.010 +00:00 [Information] It's alive!
2019-12-31 08:00:00.011 +00:00 [Information] Finished job "AliveJob" at 12/31/2019 08:00:00.
2019-12-31 08:54:18.970 +00:00 [Error] Connection refused 172.19.26.7:25
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 172.19.26.7:25
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 84
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /home/appveyor/projects/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 47
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 450
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /home/appveyor/projects/server/src/Api/Controllers/AccountsController.cs:line 146
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
2019-12-31 08:54:21.524 +00:00 [Error] Connection refused
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 84
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /home/appveyor/projects/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 47
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 450
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /home/appveyor/projects/server/src/Api/Controllers/AccountsController.cs:line 146
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by kspearrin** [comment]
It appears that your docker container cannot connect to `172.19.26.7:25`. Perhaps you have some firewall issues?

**Comment by Youness1500** [comment]
Hi kspearrin,

I create rules for smtps and is still not working.
![5](https://user-images.githubusercontent.com/53577391/71661715-5fbb5400-2d4f-11ea-8ac1-b01a3c882e02.PNG)
