### ISSUE TITLE
U2F key registration not working on Linux Host

### ISSUE THREAD

**Issue by cirk2** [bitwarden/server#664]
We've set up Bitwarden on a Linux Host with the supplied Docker scripts. So far pretty much everything works. But I've hit a Problem when Trying to register a FIDO U2F Key.

The UI Reports "Unable to complete U2F key registration." when trying to save the key registration form. 

Server logs an exception:
```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Bit.Api.Controllers.TwoFactorController.PutU2f (Api) - Validation state: Valid
U2f exception:Error when verifying signature
Could not parse:Error when verifying signature invalid key exception:U2F.Core.Exceptions.U2fException: Exception of type 'U2F.Core.Exceptions.U2fException' was thrown.
   at U2F.Core.Crypto.CryptoService.CheckSignature(ICipherParameters certificate, Byte[] signedbytes, Byte[] signature)
fail: Microsoft.AspNetCore.Identity.UserManager[0]
      Complete U2F registration error.
U2F.Core.Exceptions.U2fException: Exception of type 'U2F.Core.Exceptions.U2fException' was thrown.
   at U2F.Core.Crypto.CryptoService.CheckSignature(ICipherParameters certificate, Byte[] signedbytes, Byte[] signature)
   at U2F.Core.Models.RawRegisterResponse.CheckSignature(String appId, String clientData)
   at U2F.Core.Crypto.U2F.FinishRegistration(StartedRegistration startedRegistration, RegisterResponse tokenResponse, HashSet`1 facets)
   at Bit.Core.Services.UserService.CompleteU2fRegistrationAsync(User user, Int32 id, String name, String deviceResponse) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 353
```
This fits to the report @kspearrin made in https://github.com/brucedog/U2F_Core/issues/13 
From skimming the server repo it does not seem like the workaround using BouncyCastle has been applied here. It would be nice to have FIDO working on a linux host.

From the behavior it is the same as https://github.com/bitwarden/web/issues/462

**Comment by Hinton** [comment]
@cirk2 I don't believe this to be an issue any longer. We migrated to WebAuthn a while back which should have resolved this issue. Are you still experiencing the same issue? If not feel free to close this.

**Comment by Hinton** [comment]
Closing this, feel free to re-open it if you are still encountering issues.
