### ISSUE TITLE
HTTP 500 Error for everything but login page

### ISSUE THREAD

**Issue by TheZLabs** [bitwarden/server#694]
Set the server up and updated the certificates in config.yml to use purchased certificates. https://bitwarden.domain.com loads up fine, no ssl error. When I navigate to /admin and attempt to do the auth for the admin email, I get This page isn’t working bitwarden.domain.com is currently unable to handle this request.
HTTP ERROR 500.
So I tried the /api page, the /notifications page and all come back with error 500. When I attempt to update the cert in bwdata/ngninx/default.conf to the path where they exist in the container, or placing them at /etc/ssl/certs and key at /etc/ssl/private, it breaks the admin page entirely and I dont even get the option to enter the email address at that point. Is there another place I need to update the certificates? I also checked for ufw or firewalld and neither is running. This is being accessed internally with a valid certificate so I know its not an external firewall issue. Do I need to repoint paths in the nginx conf file? I really dont understand whats going on here. I use the software via the cloud and really like it so we were trying to set it up on premise for our organization and can't seem to make this work.

**Comment by kspearrin** [comment]
Did you place the certificates in the ./bwdata/ssl directory?

Note the comment in config.yml:

```
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
```

You should not be needing to modify nginx.conf as that is generated based on your settings in config.yml

**Comment by TheZLabs** [comment]
I wasn't modifying the nginx.conf until the rest didn't work but I changed it back. I set it up initially as you are describing, setting the certs in the config.yml and loading them to the /bwdata/ssl directory. This was the result unfortunately. So yes they are in the correct directory and they are valid certs that were purchased from GoDaddy.

**Comment by TheZLabs** [comment]
![image](https://user-images.githubusercontent.com/59536236/81321183-43faee00-9060-11ea-8115-16e685649eee.png)
The initial login page is secure so I know the certificate placement is correct. However when I try to login to the admin console, i get a 500 error after entering the email address. I have rebuilt this server 3 times now and the result has been the same each time.

**Comment by TheZLabs** [comment]
When i attempt to start Bitwarden with ./bitwarden.sh start I get this error:

Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.0, build 0a186604

Stopping bitwarden-nginx         ... done
Stopping bitwarden-admin         ... done
Stopping bitwarden-attachments   ... done
Stopping bitwarden-mssql         ... done
Stopping bitwarden-api           ... done
Stopping bitwarden-web           ... done
Stopping bitwarden-notifications ... done
Stopping bitwarden-events        ... done
Stopping bitwarden-identity      ... done
Stopping bitwarden-icons         ... done
Removing bitwarden-nginx         ... done
Removing bitwarden-admin         ... done
Removing bitwarden-attachments   ... done
Removing bitwarden-mssql         ... done
Removing bitwarden-api           ... done
Removing bitwarden-web           ... done
Removing bitwarden-notifications ... done
Removing bitwarden-events        ... done
Removing bitwarden-identity      ... done
Removing bitwarden-icons         ... done
Removing network docker_default
Removing network docker_public
Pulling mssql         ... done
Pulling web           ... done
Pulling attachments   ... done
Pulling api           ... done
Pulling identity      ... done
Pulling admin         ... done
Pulling icons         ... done
Pulling notifications ... done
Pulling events        ... done
Pulling nginx         ... done
Creating network "docker_default" with the default driver
Creating network "docker_public" with the default driver
Creating bitwarden-mssql         ... done
Creating bitwarden-icons         ... done
Creating bitwarden-identity      ... done
Creating bitwarden-notifications ... done
Creating bitwarden-events        ... done
Creating bitwarden-api           ... done
Creating bitwarden-attachments   ... done
Creating bitwarden-web           ... done
Creating bitwarden-admin         ... done
Creating bitwarden-nginx         ... done
1.33.1: Pulling from bitwarden/setup
Digest: sha256:ceaaa30350dca9dac12bf43e888947cec87633da4f0ab125e89a3e6f9d64ecdb
Status: Image is up to date for bitwarden/setup:1.33.1
docker.io/bitwarden/setup:1.33.1

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 79, Col: 11, Idx: 3478) - (Line: 79, Col: 20, Idx: 3487): Exception during deserialization
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/appveyor/projects/server/util/Setup/Context.cs:line 121
   at Bit.Setup.Program.PrintEnvironment() in /home/appveyor/projects/server/util/Setup/Program.cs:line 145
   at Bit.Setup.Program.Main(String[] args) in /home/appveyor/projects/server/util/Setup/Program.cs:line 65

**Comment by TheZLabs** [comment]
checking docker containers:

sudo docker ps
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                   PORTS                                                 NAMES
e7e06ca95a93        bitwarden/nginx:1.33.1           "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
bb24b865bd20        bitwarden/admin:1.33.1           "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-admin
e863da39e368        bitwarden/web:2.13.2             "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)                                                         bitwarden-web
7de9ce5ed0ee        bitwarden/attachments:1.33.1     "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)                                                         bitwarden-attachments
405cd8a73fa5        bitwarden/api:1.33.1             "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-api
143e7568ce8e        bitwarden/icons:1.33.1           "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-icons
f92dd7e0b45a        bitwarden/notifications:1.33.1   "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-notifications
6febbed12e90        bitwarden/identity:1.33.1        "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-identity
bd966878db7c        bitwarden/events:1.33.1          "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                              bitwarden-events
b665c23446d1        bitwarden/mssql:1.33.1           "/entrypoint.sh"    3 minutes ago       Up 3 minutes (healthy)                                                         bitwarden-mssql

**Comment by mrjlturner** [comment]
I've followed the guides and I receive the same HTTP ERROR 500 when attempting to login to the /admin portal. Looking for logging now for troubleshooting...

**Comment by mrjlturner** [comment]
UPDATE: Fixed my issue. I use MFA for Google, and had gmail setup for SMTP. I had to create an app password within my Google Account for Bitwarden to utilize to login to Gmail via secure SMTP. This fixed the problem.

**Comment by cscharf** [comment]
Thanks for the update @mrjlturner , closing this issue now, however someone from our team may want to note this scenario for an FAQ or help article in the future if anyone runs across this issue again.
