### ISSUE TITLE
After upgrade I could not login in. HTTP 500 error.

### ISSUE THREAD

**Issue by ichbinder** [bitwarden/server#704]
Hello,
after upgrade my self hosted Bitwarden system, I could not login anymore. I get this error:

```bitwarden-identity | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-identity |       Request starting HTTP/1.0 POST http://bitwarden.opentoken.de/connect/token application/x-www-form-urlencoded; charset=utf-8 228
bitwarden-identity | info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
bitwarden-identity |       CORS policy execution successful.
bitwarden-identity | info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
bitwarden-identity |       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
bitwarden-identity | crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
bitwarden-identity |       Unhandled exception: Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.
bitwarden-identity | System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.
bitwarden-identity |    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
bitwarden-identity |    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
bitwarden-identity |    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
bitwarden-identity |    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
bitwarden-identity |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
bitwarden-identity | --- End of stack trace from previous location where exception was thrown ---
bitwarden-identity |    at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
bitwarden-identity |    at Bit.Core.Repositories.SqlServer.Repository`2.CreateAsync(T obj) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/Repository.cs:line 51
bitwarden-identity |    at Bit.Core.Repositories.SqlServer.EventRepository.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/EventRepository.cs:line 73
bitwarden-identity |    at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Services/Implementations/RepositoryEventWriteService.cs:line 20
bitwarden-identity |    at Bit.Core.Services.EventService.LogUserEventAsync(Guid userId, EventType type, Nullable`1 date) in /home/appveyor/projects/server/src/Core/Services/Implementations/EventService.cs:line 66
bitwarden-identity |    at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.BuildSuccessResultAsync(User user, ResourceOwnerPasswordValidationContext context, Device device, Boolean sendRememberToken) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 128
bitwarden-identity |    at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 119
bitwarden-identity |    at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
bitwarden-identity |    at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
bitwarden-identity |    at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
bitwarden-identity |    at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
bitwarden-identity |    at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
bitwarden-identity |    at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
bitwarden-identity | ClientConnectionId:c14b047c-ec39-42dd-925b-17f124a6c81c
bitwarden-identity | Error Number:201,State:4,Class:16
bitwarden-identity | fail: Microsoft.AspNetCore.Server.Kestrel[13]
bitwarden-identity |       Connection id "0HLV5LUPNPUC1", Request id "0HLV5LUPNPUC1:00000001": An unhandled exception was thrown by the application.
bitwarden-identity | System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.
bitwarden-identity |    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
bitwarden-identity |    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
bitwarden-identity |    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
bitwarden-identity |    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
bitwarden-identity |    at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
bitwarden-identity |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)```


Is that my fault or is that a bug?

**Comment by kspearrin** [comment]
Seems like your identity container is not running on the latest version for whatever reason.

**Comment by ichbinder** [comment]
My 

''' 
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]

      Unhandled exception: Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.

System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)

   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()

   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)

   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678

   at Bit.Core.Repositories.SqlServer.Repository`2.CreateAsync(T obj) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/Repository.cs:line 51

   at Bit.Core.Repositories.SqlServer.EventRepository.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/EventRepository.cs:line 73

   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Services/Implementations/RepositoryEventWriteService.cs:line 20

   at Bit.Core.Services.EventService.LogUserEventAsync(Guid userId, EventType type, Nullable`1 date) in /home/appveyor/projects/server/src/Core/Services/Implementations/EventService.cs:line 66

   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.BuildSuccessResultAsync(User user, ResourceOwnerPasswordValidationContext context, Device device, Boolean sendRememberToken) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 128

   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 119

   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)

   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)

   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)

ClientConnectionId:0ed2bd69-ce9b-4da0-a67f-efa1e59122d6

Error Number:201,State:4,Class:16

fail: Microsoft.AspNetCore.Server.Kestrel[13]

      Connection id "0HLV6G4BFTLHS", Request id "0HLV6G4BFTLHS:00000001": An unhandled exception was thrown by the application.

System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)

   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()

   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)

   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678

   at Bit.Core.Repositories.SqlServer.Repository`2.CreateAsync(T obj) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/Repository.cs:line 51

   at Bit.Core.Repositories.SqlServer.EventRepository.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Repositories/SqlServer/EventRepository.cs:line 73

   at Bit.Core.Services.RepositoryEventWriteService.CreateAsync(IEvent e) in /home/appveyor/projects/server/src/Core/Services/Implementations/RepositoryEventWriteService.cs:line 20

   at Bit.Core.Services.EventService.LogUserEventAsync(Guid userId, EventType type, Nullable`1 date) in /home/appveyor/projects/server/src/Core/Services/Implementations/EventService.cs:line 66

   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.BuildSuccessResultAsync(User user, ResourceOwnerPasswordValidationContext context, Device device, Boolean sendRememberToken) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 128

   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/appveyor/projects/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 119

   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)

   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)

   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)

   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)

   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)

   at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, CurrentContext currentContext, GlobalSettings globalSettings) in /home/appveyor/projects/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 18

   at Bit.Core.Utilities.ServiceCollectionExtensions.<>c__DisplayClass10_0.<<UseDefaultMiddleware>b__1>d.MoveNext() in /home/appveyor/projects/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 437

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

ClientConnectionId:0ed2bd69-ce9b-4da0-a67f-efa1e59122d6

Error Number:201,State:4,Class:16

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]

      Request finished in 114.3969ms 500 '''
