### ISSUE TITLE
Updated BW/Docker, get 502 Bad Gateway

### ISSUE THREAD

**Issue by nchorekchyan** [bitwarden/server#726]
Caveat: I upgraded from centos 7 > 8 prior to this and did not check if everything was alright. Updated docker to the latest version as well as doing the bitwarden upgrade.  

The following come up as unhealthy
bitwarden/icons:1.33.1           
bitwarden/admin:1.33.1

I don't see a port for MSSQL, not sure if it should be there. I do have backups I can revert to if needed.

CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                                                 NAMES
cfb1c8088aee        bitwarden/nginx:1.33.1           "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)     80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
**04f433b2ea19        bitwarden/admin:1.33.1           "/entrypoint.sh"         45 minutes ago      Up 6 minutes (unhealthy)    5000/tcp                                              bitwarden-admin**
adae56943853        bitwarden/events:1.33.1          "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)     5000/tcp                                              bitwarden-events
**66bacf44307b        bitwarden/mssql:1.33.1           "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)                                                           bitwarden-mssql**
7ed134acfe58        bitwarden/api:1.33.1             "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)     5000/tcp                                              bitwarden-api
b222d11256ac        bitwarden/notifications:1.33.1   "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)     5000/tcp                                              bitwarden-notifications
a56fe0133b77        bitwarden/identity:1.33.1        "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)     5000/tcp                                              bitwarden-identity
**43c6d07e1d28        bitwarden/icons:1.33.1           "/entrypoint.sh"         45 minutes ago      Up 45 minutes (unhealthy)   5000/tcp                                              bitwarden-icons**
0e501eb31df1        bitwarden/web:2.13.2             "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)                                                           bitwarden-web
2ae104ec298b        bitwarden/attachments:1.33.1     "/entrypoint.sh"         45 minutes ago      Up 45 minutes (healthy)                                                           bitwarden-attachments

**Recent errors for the admin service:**

Info: Bit.Migrator.DbMigrator[12482444]
      Migrating database.
fail: Bit.Admin.HostedServices.DatabaseMigrationHostedService[0]
      Database failed to migrate.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Migrator.DbMigrator.MigrateMsSqlDatabase(Boolean enableLogging, CancellationToken cancellationToken) in /home/appveyor/projects/server/util/Migrator/DbMigrator.cs:line 41
   at Bit.Admin.HostedServices.DatabaseMigrationHostedService.StartAsync(CancellationToken cancellationToken) in /home/appveyor/projects/server/src/Admin/HostedServices/DatabaseMigrationHostedService.cs:line 40
ClientConnectionId:00000000-0000-0000-0000-000000000000
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at Bit.Admin.HostedServices.DatabaseMigrationHostedService.StartAsync(CancellationToken cancellationToken) in /home/appveyor/projects/server/src/Admin/HostedServices/DatabaseMigrationHostedService.cs:line 55
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Bit.Admin.Program.Main(String[] args) in /home/appveyor/projects/server/src/Admin/Program.cs:line 36
ClientConnectionId:00000000-0000-0000-0000-000000000000
info: Bit.Migrator.DbMigrator[12482444]
      Migrating database.
fail: Bit.Admin.HostedServices.DatabaseMigrationHostedService[0]
      Database unavailable for migration. Trying again (attempt #2)...
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Migrator.DbMigrator.MigrateMsSqlDatabase(Boolean enableLogging, CancellationToken cancellationToken) in /home/appveyor/projects/server/util/Migrator/DbMigrator.cs:line 41
   at Bit.Admin.HostedServices.DatabaseMigrationHostedService.StartAsync(CancellationToken cancellationToken) in /home/appveyor/projects/server/src/Admin/HostedServices/DatabaseMigrationHostedService.cs:line 40
ClientConnectionId:00000000-0000-0000-0000-000000000000

**Comment by kspearrin** [comment]
Looks like your mssql container is failing for some reason. Check `docker logs bitwarden-mssql`

**Comment by nchorekchyan** [comment]
Thanks,

I see the following consistently with ./bitwarden.sh restart, though admittedly I do not know which of these to investigate: 

suspect lines: 
2020-05-13 16:45:09.27 spid4s      Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2020-05-13 16:45:09.28 spid4s      An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.

Before I go crazy and figure out if need to do to restore this from a backup, can any insight be provided as if this Service Master Key is relevant. I'm not a sql guru but I can figure it out if I know this is the right direction.

Thanks for any input!

Full Log:

2020-05-13 16:45:08.01 Server      The licensing PID was successfully processed. The new edition is [Express Edition].
2020-05-13 16:45:08.58 Server      Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64) 
	Nov 16 2019 01:14:50 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)
2020-05-13 16:45:08.58 Server      UTC adjustment: 0:00
2020-05-13 16:45:08.58 Server      (c) Microsoft Corporation.
2020-05-13 16:45:08.59 Server      All rights reserved.
2020-05-13 16:45:08.59 Server      Server process ID is 32.
2020-05-13 16:45:08.59 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2020-05-13 16:45:08.59 Server      Registry startup parameters: 
	 -d /var/opt/mssql/data/master.mdf
	 -l /var/opt/mssql/data/mastlog.ldf
	 -e /var/opt/mssql/log/errorlog
2020-05-13 16:45:08.59 Server      SQL Server detected 1 sockets with 2 cores per socket and 4 logical processors per socket, 4 total logical processors; using 4 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2020-05-13 16:45:08.60 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2020-05-13 16:45:08.60 Server      Detected 6232 MB of RAM. This is an informational message; no user action is required.
2020-05-13 16:45:08.60 Server      Using conventional memory in the memory manager.
2020-05-13 16:45:08.76 Server      Buffer pool extension is already disabled. No action is necessary. 
2020-05-13 16:45:08.88 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
2020-05-13 16:45:08.89 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.
2020-05-13 16:45:08.90 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2020-05-13 16:45:08.93 Server      The maximum number of dedicated administrator connections for this instance is '1'
2020-05-13 16:45:08.94 Server      Node configuration: node 0: CPU mask: 0x000000000000000f:0 Active CPU mask: 0x000000000000000f:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2020-05-13 16:45:08.95 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2020-05-13 16:45:08.96 Server      In-Memory OLTP initialized on lowend machine.
2020-05-13 16:45:09.03 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
ForceFlush is enabled for this instance. 
2020-05-13 16:45:09.04 Server      Query Store settings initialized with enabled = 1, 
2020-05-13 16:45:09.05 spid4s      Starting up database 'master'.
2020-05-13 16:45:09.05 Server      Software Usage Metrics is disabled.
ForceFlush feature is enabled for log durability.
2020-05-13 16:45:09.27 spid4s      Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2020-05-13 16:45:09.28 spid4s      An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.
2020-05-13 16:45:09.33 spid4s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2020-05-13 16:45:09.34 spid4s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
2020-05-13 16:45:09.40 spid4s      SQL Trace ID 1 was started by login "sa".
2020-05-13 16:45:09.41 spid4s      Server name is '6f6bbacd931c'. This is an informational message only. No user action is required.
2020-05-13 16:45:09.42 spid4s      Starting up database 'msdb'.
2020-05-13 16:45:09.42 spid9s      Starting up database 'mssqlsystemresource'.
2020-05-13 16:45:09.43 spid20s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
2020-05-13 16:45:09.44 spid20s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
2020-05-13 16:45:09.45 spid9s      The resource database build version is 14.00.3257. This is an informational message only. No user action is required.
2020-05-13 16:45:09.47 spid9s      Starting up database 'model'.
2020-05-13 16:45:09.66 spid9s      Polybase feature disabled.
2020-05-13 16:45:09.67 spid9s      Clearing tempdb database.
2020-05-13 16:45:09.74 spid18s     A self-generated certificate was successfully loaded for encryption.
2020-05-13 16:45:09.75 spid18s     Server is listening on [ 'any' <ipv6> 1433].
2020-05-13 16:45:09.75 spid18s     Server is listening on [ 'any' <ipv4> 1433].
2020-05-13 16:45:09.76 spid18s     Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required.
2020-05-13 16:45:09.77 spid18s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2020-05-13 16:45:10.09 spid9s      Starting up database 'tempdb'.
2020-05-13 16:45:10.34 spid20s     The Service Broker endpoint is in disabled or stopped state.
2020-05-13 16:45:10.35 spid20s     The Database Mirroring endpoint is in disabled or stopped state.
2020-05-13 16:45:10.37 spid20s     Service Broker manager has started.
2020-05-13 16:45:10.38 spid4s      Recovery is complete. This is an informational message only. No user action is required.

**Comment by kspearrin** [comment]
I am not sure what that master key message is about, but I do not see anything in the log output that jumps out as being an issue.

**Comment by nchorekchyan** [comment]
Alright, I was able to resolve this. I have not done a deep dive but it appears to be a change with how iptables/firewalld is handled in CentOS 8 vs 7 (and I assume anything RHEL 8 based vs RHEL 7), or possibly with the different versions of docker-ce. I'm hoping the settings below are not a security issue but for my purposes this is private and not a problem.


Commands used to fix:
   sudo firewall-cmd --zone=public --add-masquerade --permanent
   sudo firewall-cmd --reload
   sudo systemctl restart docker


reference: https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8

Errors I noticed in /var/log/firewalld to trigger the investigation:

**2020-05-14 19:56:21 WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
2020-05-14 19:56:23 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:23 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-ddb5ae64554f -o br-ddb5ae64554f -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-efb55452402d -o br-efb55452402d -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-126ccace0abf -o br-126ccace0abf -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-a42e4f064bab -o br-a42e4f064bab -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-f734807ae8ab -o br-f734807ae8ab -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:25 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-c9f79e65c6fe -o br-c9f79e65c6fe -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:25 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-5d9b9fd09304 -o br-5d9b9fd09304 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:25 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-6a096f1b77e1 -o br-6a096f1b77e1 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:25 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-790d7522f724 -o br-790d7522f724 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:25 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-a0dcd9998f9d -o br-a0dcd9998f9d -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER' failed: iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION-STAGE-1' failed: iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER-ISOLATION-STAGE-1

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -F DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.

2020-05-14 19:56:44 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -X DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.

2020-05-14 19:56:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-790d7522f724 -o br-790d7522f724 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-a0dcd9998f9d -o br-a0dcd9998f9d -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:56:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:57:54 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-228aac6c179e -o br-228aac6c179e -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2020-05-14 19:57:54 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-d0fc6bb83885 -o br-d0fc6bb83885 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).**

**Comment by kubedzero** [comment]
So happy I found this. I did the same thing (Upgrade CentOS 7 to 8, following https://www.alessandronuccio.it/2020/10/21/upgrade-centos-7-to-centos-8/) and could navigate to the Bitwarden login screen but then was met with a 502 Bad Gateway on anything further.

I can confirm that running `sudo firewall-cmd --zone=public --add-masquerade --permanent; sudo firewall-cmd --reload; sudo systemctl restart docker` and then `~/bitwarden.sh restart` was able to resolve the issue for me. Thanks so much for mentioning this and digging into the firewall issues @nchorekchyan as I never would have thought to look there.

**Comment by securitytime** [comment]
I've had the same issue on CentOS 8: the containers bitwarden-admin and another one were "unhealthy".

Thanks to @nchorekchyan answer, I was able to fix it:

`firewall-cmd --add-masquerade && firewall-cmd --runtime-to-permanent`

**Comment by AbdullahZubair** [comment]
Any thoughts on Debian 11?
There is no built in firewall.

**Comment by FritschAuctores** [comment]
We had the problem because the outgoing mail server was blocked.

In this case, there is no detailed error message indicating that this is the case.

**Comment by R13e** [comment]
I also stumbled across this problem today. CentOS Stream 8, in case anyone here is still reading this. Check your 

```.bwdata/docker/docker-compose.yml```

There should be missing

```
networks:
   - default
   - public
```
   
under the services **mssql, web and attachments**. 

Add these networks and then restart 

```./bitwarden.sh```
