### ISSUE TITLE
ran -update and bitwarden/mssql:1.33.1 now failing

### ISSUE THREAD

**Issue by Zamotic** [bitwarden/server#741]
I updated my bitwarden install (Windows 10) using ./bitwarden.ps1 -update

After the update ran I noticed the following error message after "Migrating database.":
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 193
   at Bit.Setup.Program.Update() in /home/appveyor/projects/server/util/Setup/Program.cs:line 140
   at Bit.Setup.Program.Main(String[] args) in /home/appveyor/projects/server/util/Setup/Program.cs:line 65
ClientConnectionId:00000000-0000-0000-0000-000000000000
Database update complete

When I check the logs for Bitwarden-mssql I see the following message over and over:
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)

Any ideas on how to resolve that?

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/server/issues/725

**Comment by Zamotic** [comment]
Wow, you're super quick. My apologies, didn't think to search closed tickets.

Thanks for the reference. Downgrading Docker Desktop now.
