### ISSUE TITLE
Self Hosted Admin UI - Value cannot be null. (Parameter 'email')

### ISSUE THREAD

**Issue by fbonelle** [bitwarden/server#779]
Hello,

I can not connect to the admin UI. I have 2 mail address in global.override.env.

Below, the trace I have in admin log:
>`2020-06-14` 22:18:54.400 +00:00 [Error] Value cannot be null. (Parameter 'email')
System.ArgumentNullException: Value cannot be null. (Parameter 'email')
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Bit.Core.Identity.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String token, Boolean isPersistent) in /home/appveyor/projects/server/src/Core/Identity/PasswordlessSignInManager.cs:line 60
   at Bit.Admin.Controllers.LoginController.Confirm(String email, String token, String returnUrl) in /home/appveyor/projects/server/src/Admin/Controllers/LoginController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-06-14 22:18:54.793 +00:00 [Error] Value cannot be null. (Parameter 'email')
System.ArgumentNullException: Value cannot be null. (Parameter 'email')
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Bit.Core.Identity.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String token, Boolean isPersistent) in /home/appveyor/projects/server/src/Core/Identity/PasswordlessSignInManager.cs:line 60
   at Bit.Admin.Controllers.LoginController.Confirm(String email, String token, String returnUrl) in /home/appveyor/projects/server/src/Admin/Controllers/LoginController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-06-14 22:18:55.076 +00:00 [Error] Value cannot be null. (Parameter 'email')
System.ArgumentNullException: Value cannot be null. (Parameter 'email')
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Bit.Core.Identity.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String token, Boolean isPersistent) in /home/appveyor/projects/server/src/Core/Identity/PasswordlessSignInManager.cs:line 60
   at Bit.Admin.Controllers.LoginController.Confirm(String email, String token, String returnUrl) in /home/appveyor/projects/server/src/Admin/Controllers/LoginController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

I am trying to find what is my problem for hours, but I don't find how to solve my issue.

Thanks

**Comment by kspearrin** [comment]
Can you paste the redacted global.override.env settings?

**Comment by fbonelle** [comment]
Hello,

Here is my global.override.env:

globalSettings__baseServiceUri__vault=https://<url>.biz
globalSettings__baseServiceUri__api=https://<url>/api
globalSettings__baseServiceUri__identity=https://<url>/identity
globalSettings__baseServiceUri__admin=https://<url>/admin
globalSettings__baseServiceUri__notifications=https://<url>/notifications
globalSettings__sqlServer__connectionString="Data Source=tcp:mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=<password>;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"
globalSettings__identityServer__certificatePassword=<certPassword>
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://<url>/attachments
globalSettings__dataProtection__directory=/etc/bitwarden/core/aspnet-dataprotection
globalSettings__logDirectory=/etc/bitwarden/logs
globalSettings__licenseDirectory=/etc/bitwarden/core/licenses
globalSettings__internalIdentityKey=<internalIdentityKey>
globalSettings__duo__aKey=<aKey>
globalSettings__installation__id=<install_id>
globalSettings__installation__key=<install_key>
globalSettings__yubico__clientId=REPLACE
globalSettings__yubico__key=REPLACE
globalSettings__mail__replyToEmail=<reply_email>
globalSettings__mail__smtp__host=smtp.orange.fr
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=<email>
globalSettings__mail__smtp__password=<smtp_password>
globalSettings__disableUserRegistration=false
globalSettings__hibpApiKey=REPLACE
adminSettings__admins=<admin_mail1>,<admin_main2>

**Comment by kspearrin** [comment]
Looks to me like something may be wrong with the link you are clicking from your email. Try copy/pasting the link rather than clicking on it.

**Comment by fbonelle** [comment]
Sorry, I don't undestand :(

**Comment by FreakyTea** [comment]
Hi :)

getting the Same error. i installed bitwarden behind nginx as reverse proxy, following this Tutorial [https://dennisnotes.com/note/20181112-bitwarden-server/](https://dennisnotes.com/note/20181112-bitwarden-server/)

my nginx config:

`server {

	server_name <url>;
	root /var/www/<folder>;

	index index.html;

	location / {
		proxy_pass http://localhost:5178/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		client_max_body_size 0;
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
		add_header Referrer-Policy "same-origin";

		access_log /var/log/nginx/bitwarden/access.log;
		error_log /var/log/nginx/bitwarden/error.log;
	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<url>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<url>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = <url>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80 ipv6only=on;

	server_name <url>;
    return 404; # managed by Certbot


}`

in my config.yml i have `http_port = 5178` and `https_port = 5179` as well as `url: https://<url>`

my global settings are all with `https` before URLs, i get the mails so this works fine

My Mail Link looking like:

`https://<url>/admin/login/confirm?returnUrl=%2fadmin&amp;email=<user>%40<domain>&amp;token=CfDJ8LnbSc8OeApDt6S%2bqgrxWoS7JoKZQlbI1lGrdLifV%2bZ4s5DJ%2fBxajjApV4x2l9kPvHoS0fSFQmjW53wxsbo0nBqVju9OqzAq90JVCLHEnvrQJKCZKim%2bxfG6XWSOFLD2GWGR3eftX%2fZiq3DG7I73Zrpn8h7pAdVMyIHt%2bpbIkR4owwWlKcsd0pso0Z%2bjYXnZmXk7dbo0Gp7vyzsZJhQfbkQapH6KxHAktMYzFTTsIgl7`

hope this helps...
