### ISSUE TITLE
Database upgrade issue

### ISSUE THREAD

**Issue by qovert** [bitwarden/server#792]
Having an issue upgrading an onprem bitwarden host. 

OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

Steps taken: 
bitwarden.sh updateself 
bitwarden.sh update

On advice from other issues, I waited and attempted a bitwarden.sh updatedb and received the same result: 

Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.18.0, build 8dd22a9

Status: Image is up to date for bitwarden/setup:1.34.0

Migrating database.
Database is in script upgrade mode. Trying again (attempt #2)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #3)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #4)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #5)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #6)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #7)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #8)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #9)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #10)...
Migrating database.
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 193
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 190
   at Bit.Setup.Program.Update() in /home/appveyor/projects/server/util/Setup/Program.cs:line 140
   at Bit.Setup.Program.Main(String[] args) in /home/appveyor/projects/server/util/Setup/Program.cs:line 65
ClientConnectionId:cbe6f208-f2c2-424f-8e10-e04fe52cff6d
Error Number:18401,State:1,Class:14

Checking out the errorlog in the mssql container yielded this: 

2020-06-24 20:12:22.78 Logon       Error: 18401, Severity: 14, State: 1.
2020-06-24 20:12:22.78 Logon       Login failed for user 'sa'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.

**Comment by qovert** [comment]
I figured it out. There was a zombie process in the bitwarden-mssql container. Once that was taken care of, I: 
./bitwarden.sh restart
./bitwarden.sh update
./bitwarden.sh updatedb

Migration was successful and the output of docker container ps became healthy. Thanks!
