### ISSUE TITLE
mssql connection error

### ISSUE THREAD

**Issue by RohithPoyyeri** [bitwarden/server#967]
When I am trying to self host in an AWS EC2 Ubuntu instance, I reckon everything worked fine and I have attached DNS, SSL certificate and a CloudFlare firewall.
I followed this link https://rtfm.co.ua/en/bitwarden-an-organizations-password-manager-self-hosted-version-installation-on-an-aws-ec2.

When I am trying to register a new user I am getting HTTP 500 error, here is the docker api logs

`Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "PostRegister", controller = "Accounts"}. Executing controller action with signature System.Threading.Tasks.Task PostRegister(Bit.Core.Models.Api.RegisterRequestModel) on controller Bit.Api.Controllers.AccountsController (Api).
fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      Format of the initialization string does not conform to specification starting at index 130.
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 130.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Bit.Core.Repositories.SqlServer.UserRepository.GetByEmailAsync(String email) in /home/runner/work/server/server/src/Core/Repositories/SqlServer/UserRepository.cs:line 30
   at Bit.Core.Identity.UserStore.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken) in /home/runner/work/server/server/src/Core/Identity/UserStore.cs:line 54
   at Bit.Core.Identity.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken) in /home/runner/work/server/server/src/Core/Identity/UserStore.cs:line 78
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user, ICollection`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at Bit.Core.Services.UserService.RegisterUserAsync(User user, String masterPassword, String token, Nullable`1 orgUserId) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 292
   at Bit.Api.Controllers.AccountsController.PostRegister(RegisterRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/AccountsController.cs:line 77
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Bit.Core.Models.Api.ErrorResponseModel'.`

Here is the output of  docker ps

`b8054a9397cf        bitwarden/nginx:1.37.2           "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx

217af7766296        bitwarden/admin:1.37.2           "/entrypoint.sh"    15 minutes ago      Restarting (139) 14 seconds ago                                                         bitwarden-admin

dfc122644946        bitwarden/portal:1.37.2          "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp                                              bitwarden-portal

9ecab48c875f        bitwarden/identity:1.37.2        "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp                                              bitwarden-identity

49cb549133b3        bitwarden/api:1.37.2             "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp                                              bitwarden-api

e00ebf5ae00a        bitwarden/web:2.16.2             "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)                                                                 bitwarden-web

d991f3f305f4        bitwarden/notifications:1.37.2   "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp       bitwarden-notifications
e0a6bd63d7bc        bitwarden/mssql:1.37.2           "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)                                                                 bitwarden-mssql

72359b0cb2d8        bitwarden/attachments:1.37.2     "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)                                                                 bitwarden-attachments

555246eefc12        bitwarden/events:1.37.2          "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp                                              bitwarden-events

301d995cdf69        bitwarden/icons:1.37.2           "/entrypoint.sh"    15 minutes ago      Up 15 minutes (healthy)           5000/tcp                                              bitwarden-icons

95cd8a9a2cc1        bitwarden/sso:1.37.2             "/entrypoint.sh"    15 minutes ago      Up 15 minutes (unhealthy)         5000/tcp                                              bitwarden-sso`

Any help is highly appreciated.

**Comment by kspearrin** [comment]
Looks like your connection string isn't formatted correctly or something. Check the bwdata/env/global.override.env file

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
