### ISSUE TITLE
Issue adding 2FA Yubikey 5C NFC using USB-C port

### ISSUE THREAD

**Issue by ThanosGkara** [bitwarden/server#980]
Dear all,

When we try to add a 2FA yubikey 5C the our self hosted installation returns a 500 on **/api/two-factor/yubikey**.

Our version is **2.16.2**.

Error from the API itself.

`2020-11-03 08:59:55.513 +00:00 [Error] The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at YubicoDotNetClient.YubicoClient.SetApiKey(String apiKey)
   at YubicoDotNetClient.YubicoClient..ctor(String clientId, String apiKey)
   at Bit.Core.Identity.YubicoOtpTokenProvider.ValidateAsync(String purpose, String token, UserManager`1 manager, User user) in /home/runner/work/server/server/src/Core/Identity/YubicoOtpTokenProvider.cs:line 69
   at Microsoft.AspNetCore.Identity.UserManager`1.VerifyTwoFactorTokenAsync(TUser user, String tokenProvider, String token)
   at Bit.Api.Controllers.TwoFactorController.ValidateYubiKeyAsync(User user, String name, String value) in /home/runner/work/server/server/src/Api/Controllers/TwoFactorController.cs:line 399
   at Bit.Api.Controllers.TwoFactorController.PutYubiKey(UpdateTwoFactorYubicoOtpRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/TwoFactorController.cs:line 124
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

![image](https://user-images.githubusercontent.com/7399553/97966159-bc4a2e00-1dbb-11eb-8c77-87116351d170.png)

The other stadard of **fido U2F** works fine with the same key.

**Comment by kspearrin** [comment]
Did you register with yubico to get an api key? See our install docs.

**Comment by ThanosGkara** [comment]
Just gave a look at it. Thank you very much.

**Comment by cscharf** [comment]
Hi @ThanosGkara , it's been a while and we haven't heard from you. I'm closing this issue for now but please let us know if you're still experiencing this issue after registering and checking the install docs.
