### ISSUE TITLE
Enforce email 2fa if joining org with policy

### ISSUE THREAD

**Issue by Kuchenm0nster** [bitwarden/server#996]
If a user joins an org that requires 2FA via policy by using SSO and that user is registering a new account, the email 2fa should be activated by default. Else the org admin can't Confirm the user.
If you try to confirm the user you don't get any feedback of the missing 2fa but an error in the browser console:

`
ERROR Error: Uncaught (in promise): t: {"response":{"Object":"error","Message":"User does not have two-step login enabled.","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null},"message":"User does not have two-step login enabled.","validationErrors":null,"statusCode":400}
`

Just like #658

**Comment by kspearrin** [comment]
Hmm. From my understanding the linked PR does exactly what you just described. I am not sure how you are ending up in the scenario decribed.

**Comment by Kuchenm0nster** [comment]
Strange, since the new release I can't reproduce the error because I have a new one.
After the successful login in our SSO portal i get the following error /sso/Account/ExternalCallback:
`Error
There was an unexpected error during single sign-on. Please close this page and try again. Cannot insert the value NULL into column 'ApiKey', table 'vault.dbo.User'; column does not allow nulls. INSERT fails. The statement has been terminated.`

with the following Stacktrace:
`An unhandled exception has occurred while executing the request.
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'ApiKey', table 'vault.dbo.User'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 678
   at Bit.Core.Repositories.SqlServer.Repository`2.CreateAsync(T obj) in /home/runner/work/server/server/src/Core/Repositories/SqlServer/Repository.cs:line 51
   at Bit.Core.Identity.UserStore.CreateAsync(User user, CancellationToken cancellationToken) in /home/runner/work/server/server/src/Core/Identity/UserStore.cs:line 38
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Bit.Core.Services.UserService.RegisterUserAsync(User user) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 308
   at Bit.Sso.Controllers.AccountController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims, String userIdentifier) in /home/runner/work/server/server/bitwarden_license/src/Sso/Controllers/AccountController.cs:line 460
   at Bit.Sso.Controllers.AccountController.ExternalCallback() in /home/runner/work/server/server/bitwarden_license/src/Sso/Controllers/AccountController.cs:line 221
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Bit.Sso.Utilities.SsoAuthenticationMiddleware.Invoke(HttpContext context) in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/SsoAuthenticationMiddleware.cs:line 80
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, CurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 19
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

This happens when when using sso to create a new user without an invitation to the organization

**Comment by kspearrin** [comment]
@addisonbeck See above error please. Can you confirm your database is up to date? Run `bitwarden.sh updatedb`

**Comment by cscharf** [comment]
A DB update should correct/fix that exception/error with the latest server version.

**Comment by Kuchenm0nster** [comment]
I ran the DB update thats why there is apikey NOT NULL.
My guess is [RegisterUserAsync](https://github.com/bitwarden/server/blob/028ad46c47d2dc5d33cbcedbb29549563a161324/src/Core/Services/Implementations/UserService.cs#L257-316) without a masterpassword is used in the event of SSO user registration.
There the user gets created and persisted without getting the [TwoFactorProviderType.Email](https://github.com/bitwarden/server/blob/028ad46c47d2dc5d33cbcedbb29549563a161324/src/Core/Services/Implementations/UserService.cs#L281) and the [ApiKey](https://github.com/bitwarden/server/blob/028ad46c47d2dc5d33cbcedbb29549563a161324/src/Core/Services/Implementations/UserService.cs#L295)

**Comment by cscharf** [comment]
🤦🏻 , sorry @Kuchenm0nster , we've now been able to reproduce this and have other reports coming into our customer success team/support; we're actively working on a fix and will patch it ASAP.

**Comment by Kuchenm0nster** [comment]
Glad I could help


Am 18. November 2020 15:27:36 schrieb Chad Scharf <notifications@github.com>:

🤦🏻 , sorry @Kuchenm0nster<https://github.com/Kuchenm0nster> , we've now been able to reproduce this and have other reports coming into our customer success team/support; we're actively working on a fix and will patch it ASAP.

**Comment by cscharf** [comment]
@Kuchenm0nster , that ApiKey error should be resolved now. The original issue regarding the 2FA policy, can you please describe some additional details on reproduction of that issue?

**Comment by Kuchenm0nster** [comment]
Steps to reproduce:
1. Create organization
2. Set 2FA policy for organization
3. Enable SSO for organization
4. Use Enterprise SSO to login with new bitwarden user (user not created or invited in bitwarden)

At this point the admin of the organization can see the newly created user but can't confirm him.
In console you get the error described above.
The user does not have email 2fa enabled. Maybe it has to be enabled in `bitwarden_license/src/Sso/Controllers/AccountController.cs` just like you did here?
 https://github.com/bitwarden/server/blob/58eb0510ca42fda355f7e13b3b71ac45bdeffb0d/src/Core/Services/Implementations/UserService.cs#L279-L291

**Comment by vincentsalucci** [comment]
Pending internal testing, this issue should be resolved 👍

**Comment by Kuchenm0nster** [comment]
Just wanted to give some feedback.
I updated to the 1.38.2 and it's working just like I expected.
Thanks
